Post.create!(title: "Rudimental – Spoons feat. MNEK & Syron (Two Inch Punch Remix)", body: "(Black Butter Records) Rudimental are a quartet from Hackney who have gone from strength to strength since the release of their single ‘Feel The Love’ in 2012. The group are renowned for their high energy performances on stage and are due to start their own headline tour in April 2013, which I hope to get tickets to. Rudimental have managed to secure top quality vocalists for their singles and this time they’ve teamed up with MNEK and Syron, deciding not to enlist the help of John Newman on this occasion. I particularly like the Two Inch Punch Remix of this track. I first caught wind of this producer a few years back when a friend found the Birdy track ‘People Help The People‘ remix. Again going in with the distorted vocals and rolling bass this tune is somehow both cold and warming at the same time. Have a listen a see what you think. If you go to the sites website you can get hold of this remix for free in exchange for your email, or just steam it below.", soundcloud: "https://soundcloud.com/rudimentaluk/spoons-two-inch-punch-remix", youtube: "https://www.youtube.com/watch?v=a9iZh5lV13M", created_at: DateTime.new(2013, 2, 8))

Post.create!(title: "London Grammar – Hey Now", body: "This track is both beautiful and haunting in equal measures. There isn’t much info about this band other than that they are a ‘London trio’ consisting of Hannah, Daniel and Dot. This tune has an air of The XX about it, with the strong female vocal, soft reverberating drums and floating guitars. The Dot Major Remix gives it a nice twist if you’re after something with a higher BPM. Check it out below. Perfect hangover music.", youtube: "https://www.youtube.com/watch?v=MTvHcQmKUpU", soundcloud: "https://soundcloud.com/londongrammar/hey-now-dot-major-remix", created_at: DateTime.new(2013, 2, 8))

Post.create!(title: "Chris Malinchak – So Good To Me", body: "(French Express) I heard this track a few months back on my way to a 12 hour nights shift and it made me smile. Any song capable of doing that I think deserved to be shared. A true feel good tune by the NYC producer. Great melodies with soulful vocals. A class act all the way.", soundcloud: "https://soundcloud.com/chrismalinchak/so-good-to-me", created_at: DateTime.new(2013, 2, 4))

Post.create!(title: "Jeremy Olander – Let Me Feel", body: "(Pryda Friends) I have to say this talented Swede is fast becoming my new favorite producer. Not only did he give away his last two tracks, ‘Put Out’ and ‘Pusher‘ for free, but the quality seems to improve with each new release. But then with a mentor like Eric Prydz, quality is to be expected. His tracks have a certain air of early Deadmau5 to them, and I feel he is well on his way to establishing himself as a house hold name in progressive music. This tune builds beautifully, with great melodies and a catchy vocal – textbook anthemic house music. I for one cannot wait for new material from Mr Olander, but am happy listening to this top quality track in the mean time.", soundcloud: "https://soundcloud.com/jeremyolander/jeremy-olander-let-me-feel", created_at: DateTime.new(2013, 2, 4))

Post.create!(title: "Fly O Tech - Spacetacular", body: "(Cream Couture Records) Demian Muller and Ernesto Yoga make up Fly O Tech. Muller is on vocals while Yoga is a multi-instrumenalist in the duo. “Beginning with watery electronic beats, to feel and follow the dancing rain right through and into your soul, Fly-O-Tech pulls, swims in deeper emotions, but comforts that this slow drop will be lifted. If not by the sweet vocals, then by the beautiful symphony of life captured by a solo piano. The rain falls, the music plays, you wade through the beats, and then that call – a completed circle of a personal and unified journey, created for you by Fly-O-Tech.” Or so their Soundcloud page says. I’m no so sure about all that, but I do know that I really enjoy this track, and I hope you do to. Their new track Twilight is also well worth a listen.", youtube: "https//www.youtube.com/watch?v=TzVzQn-zM5M", created_at: DateTime.new(2013, 1, 22))

Post.create!(title: "A$AP Rocky - Wild For The Night", body: "(Columbia) What do you get when you cross arguably the biggest name in dub step with one of the most exciting new rappers on the scene? This track. After releasing a few mixtapes this is the debut single from Rakim Mayers’ first full length album; Long Live A$AP. I’ve been a fan of A$AP since I first heard Goldie last year. I’ll admit I wasn’t sure about this track when I first heard it but it’s really grown on me.", soundcloud: "https://soundcloud.com/asvpxrocky/wild-for-the-night", created_at: DateTime.new(2013, 1, 21))

Post.create!(title: "Harlem Shake", body: "Legendary Hip Hop producer Justin Smith aka Just Blaze, has teamed up with one of the champions of Trap music to make this absolute banger. Baauer Has been going from strength to strength since releasing one of the biggest underground tracks of last year – Harlem Shake. Enjoy this pairing, just be careful you don’t blow your speakers!", created_at: DateTime.new(2013, 1, 21))

Post.create!(title: "Justin Martin - Don't Go (Dusky Remix)", body: "(Dirtybird Records) I am a big fan of the original version of this track by the co-founder of the Dirtybird crew, but the Dusky remix gives it a nice twist. The Lodon duo have steadily been gaining momentum and 2013 looks set to be a big year for them. Watch this space.", youtube: "https://www.youtube.com/watch?v=ANP_BkWVkLI", created_at: DateTime.new(2013, 1, 12))

Post.create!(title: "Jamie Woon - Wayfaring Stranger (Burial Mix)", body: "I like many people am rather excited by the news that the living legend Burial is releasing new material. Here he is remixing Jamie Woon. This is one of my all time favorite tracks, deep dark and full of emotion. Hit play and enjoy the journey.", youtube: "https://www.youtube.com/watch?v=HSe4CxEvFiE", created_at: DateTime.new(2012, 12, 14))

Post.create!(title: "Kuhn - I Quit (Time Wharp Remix)", body: "(Civil Music) I’m liking this Time Wharp remix. Available on Kuhn’s ‘Kings’ EP which you can get hold of here. This deep rolling track is cooler than Jay Z’s fridge.", youtube: "https://www.youtube.com/watch?v=4LlCbq7KXi8", created_at: DateTime.new(2012, 12, 14))