# Post.create!(title: "", body: "", soundcloud: "")
Post.create!(title: "Years & Years – Real", body: "I heard this track a couple of weeks ago and it’s really grown on it. It comes from London trio Years & Years. This one is the title track from their ‘Real‘ EP which was released on 17 Feb under Kitsune. Have a listen and see what you think. If this is up your street, they’ve just added their latest track to their soundcloud page.", soundcloud: "https://soundcloud.com/kitsune-maison/years-years-real-original-mix")

Post.create!(title: "Cyril Hahn & Javeon – Breaking", body: "Oh yes people, new material from the man Cyril Hahn. The follow up to his first original track ‘Perfect Form‘, comes in the guise of ‘Breaking‘. This time he’s recruited the help of  fellow PMR signing Javeon for vocal duties. It will form part of a new compilation album to be released by PRM, called ‘20 square feet in action‘, with an as yet unconfirmed released date. To celebrate this the legendary London based label have organised a european tour ,headlined by the man himself, Mr Hahn.  Make sure you get hold of a ticket as this will be a rather tasty gig.", soundcloud: "https://soundcloud.com/cyrilhahn/cyril-hahn-javeon-breaking")

Post.create!(title: "BANKS – Brain", body: "Hold up people, here some new stuff from one our firm favourites here on medicinalsounds.com - BANKS. This time the the L.A. beauty has teamed up with yet another key player in electronic scene with Schlomo taking on production duty. Just one more legendary producer to add to the list of artists she’s worked with, and it’s another perfect match. Slow and pensive with echoing claps and deep bass set up the stage for BANKS’ mesmerising vocals. It’s yet another track to get us salivating at the thought of the forthcoming debut album expect later this year.", soundcloud: "https://soundcloud.com/banksbanksbanks/banks-brain-prod-by-shlohmo")

Post.create!(title: "ASTR – Operate", body: "Time for a bit of sexy synth pop, in the form of NYC duo ASTR and their debut single ‘Operate‘. I’ve been playing this tune on my travels, and smooth 80′s vibes always puts me a good mood. “Call me the Doctor” – seem apt for medicinalsounds.com. If you like this then their latest offering, ‘We Fall Down‘ is another 80′s inspired piece from the same vein. Or check out ‘The Drum Remix‘ for a slowed down, even more sultry version of the original.", soundcloud: "https://soundcloud.com/astrtv/astr-operate")

Post.create!(title: "Hey Now – London Grammar (Arty Remix)", body: "As mentioned in my previous post there’s a whole host of music I’ve been enjoying over the past few months that I want to get up on the site. So without further ado here’s one of those tracks. It’s an epic remix of Medicinal Sounds’ favourite, London Grammar, by the young Russian Arty. He takes their break through track ‘Hey Now’ and give a tasty reworking making it suitable for the big room. Arty keeps Hannah Reid’s sublime vocals shining through whist adding in deep bass and uplifting synths, all combined to make a really special remix. This tracks been doing the rounds since late last year, so may be old news to some, but hopefully will be a new treat for a few of you.", soundcloud: "https://www.youtube.com/watch?v=LglFEjlGM48")

Post.create!(title: "Embe – Welcome To My House Mix", body: "Apologies loyal followers. It has been all quiet on the Medicinal Sounds front for far too long. With the festivities of Yuletide and a trip to the USA, medicinalsounds.com was sadly neglected. But fear not, as with a new year comes new music and there’s a whole host of tracks that I’ve been listening to that need some love on the site. But back to business, as this post is *fanfare* the 100th post on medicinalsounds.com. So to celebrate here is a mix of my favourite House and Deep House tracks from the blog over the past year. It was recorded live, in one take with no post production editing, so some of the mixing isn’t as tight as I’d like it to be, but I hope you enjoy. Now I’ve finally got my set up working properly, there’ll be more mixes in the near future. Welcome to 2014. Welcome To My House Mix", soundcloud: "https://soundcloud.com/official-medicinal-sounds/house-deep-house-mix")

Post.create!(title: "Hackman – Change My Life", body: "The latest offering from Hackman is sounding real good. ‘Change My Life‘, is a chilled slice of  delicious house that has been getting a lot of plays from myself. The whole EP is beautifully crafted piece of work with deep bass lines balanced against uplifting melodies. If you like this, then check out the remix Hackman did for my friends Eli and Fur track ‘Nightmares‘.", soundcloud: "https://soundcloud.com/futureboogie/change-my-life-sd-192-01")

Post.create!(title: "Bonobo – First Fires Ft. Grey Reverend (Maya Jane Coles Remix)", body: "The supremely talented Maya Jane Coles has put her hand to Bonobo’s ‘First Fires‘. Taken from his  album ‘The North Borders’ Coles has put her usual intoxicating deep feel to the track. I can’t think of a remix that Maya has put out that I haven’t played to death, and I feel this one will be no exception. Beautifully deep and augmenting the original quality put down by Bono. Top work once again from both artists.", soundcloud: "https://soundcloud.com/mayajanecoles/bonobo-first-fires-feat-grey-1")

Post.create!(title: "Metronomy – I’m Aquarius", body: "Indie-dance producer Joe Mount, aka Metronomy is set to release his follow up to ‘The English Riviera‘ in the form of his new album ‘Love Letters‘. Taken from the LP is ‘I’m Aquarius’. It’s a stripped back steady number, which reminds me of Friendly Fire’s ‘Paris’ to a certain extent. Mount started his musical life as a drummer before moving into production, and the clean simple percussion is at the hear of this track. I’m told that you can access the track through the Night Sky mobile app, by locating the Aquarius constellation in the sky. I’ll be honest I haven’t checked if this is true, but free find out and let me know.", soundcloud: "https://soundcloud.com/kwabs/kwabs-last-stand")

Post.create!(title: "Rosie Lowe – Right Thing", body: "(37 Adventures) Here’s some new music from an exciting new talent, Miss Rosie Lowe. The South London based singer has teamed up with Dave Okumu on production to create this number. Its starts of as a stripped back piano ballad, but soon descends into a tripped out etherial piece, not too far removed from some of James Blakes’ earlier work. There is real sense of familiarity when listening to this track, with similarities sure to be drawn to BANKS, but that’s not to take anything away from Rosie’s talent, and there are definitely worse be to be compared to. Looking forward to hearing new stuff from Rosie Lowe soon.", soundcloud: "https://soundcloud.com/rosielowe/rosie-lowe-right-thing")

Post.create!(title: "Laura Mvula – Sing To The Moon (Klangkarussell Remix)", body: "(Universal) After their feel good summer smash hit ‘Sonnentanz’, Klangkarussell turn their attention to Laura Mvula’s ‘Sing To The Moon’. The Austrian duo of Tobias Rieser and Adrian Held have taken the Laura’s original and kept things downtempo, whist giving it a smooth warm makeover. With an album currently being created, expect to hear a lot more from Klangkarussel in the near future.", soundcloud: "https://soundcloud.com/klangkarussell/sing-to-the-moon-laura-mvula")

Post.create!(title: "White Lies – Change (Dawn Golden Remix)", body: "Dawn Golden (aka Dexter Tortoriello) takes on the White Lies’ ode to heartbreak, ‘Change‘. Dawn Golden takes the track deeper, with a catchy melody and alluring synths; epic in every sense. Its another melancholy beautiful piece of work by  Tortiello, and with a full album set to drop early next year, expect to hear from this young man in the near future.", soundcloud: "https://soundcloud.com/dawn-golden/white-lies-change-dawn-golden")

Post.create!(title: "Mass Digital – Feel So Good", body: "(Audio Tonic) Serbian producer Mass Digital, aka Boris Mijolic is set to release his ‘Feel So Good‘ EP on 09/11/13 on Dubai’s Audio Tonic label. The title track of the same name is a slowed down tempo number with acid-tinged bass and entrancing melodies all set around solid drums. Mijolic has been steadily gaining moment in recent years with releases on Neurotraxx, Frequenza and Pacha Recordings. This EP is another statement of intent as Mijolic treads the melodic line between techno and house.", soundcloud: "https://soundcloud.com/official-medicinal-sounds/mass-digital-feel-so-good")

Post.create!(title: "Laura Welsh – Undiscovered (Blonde Remix)", body: "(Outsiders/ Polydor Records) Every so often I get a bit obsessed with a song. At the moment that is happening with the Blonde remix of Laura Welsh’s track ‘Undiscovered‘. It’s one of those delicious house reworks of an already beautiful track that just works. The Bristol based duo of Jake Manson and Adam Englefield have taken the chilled out original and given it a little house work over, with smooth bass line and upped tempo, all the while keeping Laura’s gorgeous vocals shining through. Sounding good.", soundcloud: "https://soundcloud.com/laurawelsh/laura-welsh-undiscovered")

Post.create!(title: "Moonbeam – Cocoon (Sunset Remix)", body: "Sorry for the lack of activity over the past week, been working some crazy hours to try and get some cash flow in. But back to the matter at hand. Time to add another tune into the ‘Classic Cuts‘ vault. This time its the Russian Khaleev brother’s Moonbeam who take their place, with the Sunset remix of their own track ‘Cocoon‘. It’s dreamy placid reworking as the title suggests, with the beat gently ebbing along before the high bubbling synths come in. This tune has such good memories for me – laying in a park, in the sunshine with a few beers and nothing to do for the rest of the day. Warming thoughts as the weather turns cold here in rainy old England.", soundcloud: "https://soundcloud.com/tune-of-the-week/moonbeam-cocoon-sunset-mix")

Post.create!(title: "Movement – Us", body: "(Modular) Sydney based trio, Movement, drop their second single ‘Us’. It’s a dark emotive affair and upon closer inspection the lyrics go a little deeper than a lot of other electronic artists around at the moment. The slowed tempo and almost whispered vocals remind me of Jai Paul’s ‘Jasmin‘, which to be fair, is no bad thing. I’ve been playing this to death for the past few weeks and it’s still sounding good.", soundcloud: "https://soundcloud.com/modularpeople/movement-us-1")

Post.create!(title: "Breach – Everything You Never Had (Joe Goddard Remix)", body: "(Atlantic Records) As you can probably tell, Medicinal Sounds is undergoing to bit of cosmetic work at the moment. But don’t worry while we give the site a lick of new paint we’ll continue to bring you great new music. As proof here’s the delicious Joe Goddard Remix of Breach’s ‘Everything You Never Had’. The original is the next release from Breach (aka Ben Westbeech) after his summer smash ‘Jack’. It takes a slightly more old school feel, with the soulful vocals of Andreya Triana. Breach has promised a full album release in 2014 which I’m sure many people are waiting for with bated breath. Now onto the remix, let’s be honest Mr Goddard seems to be able to do no wrong at the moment. He has well and truly established himself as one of the heavyweights in House music, whether it be as one half of the Two Bears, playing with Hot Chip, or just by himself as a producer. His take on ‘Everything You Never Had’ is another entry into a pretty flawless and extensive back catalogue. The memorising loop and bird sounds give a warming feeling of calm. Top quality work once again from the big man.", soundcloud: "https://soundcloud.com/breach-uk/everything-you-never-had-joe-goddard")

Post.create!(title: "Kyle Watson – Throwback (Black Loops Remix)", body: "Kyle Watson’s new ‘Throwback‘ EP is due for release on 28th October this year. The South African has been rising up the ranks over the past few years, working with various labels before releasing this EP on Gruuv. He brings his trademark rugged house sound to the outfit that will be sure to fit in perfectly. ‘Throwback‘ is comprised of three original tracks and one remix from the Italian born, Berlin based duo Black Loops.  Gruuv’s newest signing put their own spin on ‘Throwback’, giving it a more dubbed out, deeper feel.", soundcloud: "https://soundcloud.com/gruuv/kyle-watson-throwback-black")