# Post.create!(title: "", body: "", soundcloud: "")
Post.create!(title: "Years & Years – Real", body: "I heard this track a couple of weeks ago and it’s really grown on it. It comes from London trio Years & Years. This one is the title track from their ‘Real‘ EP which was released on 17 Feb under Kitsune. Have a listen and see what you think. If this is up your street, they’ve just added their latest track to their soundcloud page.", soundcloud: "https://soundcloud.com/kitsune-maison/years-years-real-original-mix", created_at: DateTime.new(2014, 2, 23))

Post.create!(title: "Cyril Hahn & Javeon – Breaking", body: "Oh yes people, new material from the man Cyril Hahn. The follow up to his first original track ‘Perfect Form‘, comes in the guise of ‘Breaking‘. This time he’s recruited the help of  fellow PMR signing Javeon for vocal duties. It will form part of a new compilation album to be released by PRM, called ‘20 square feet in action‘, with an as yet unconfirmed released date. To celebrate this the legendary London based label have organised a european tour ,headlined by the man himself, Mr Hahn.  Make sure you get hold of a ticket as this will be a rather tasty gig.", soundcloud: "https://soundcloud.com/cyrilhahn/cyril-hahn-javeon-breaking", created_at: DateTime.new(2014, 2, 6))

Post.create!(title: "BANKS – Brain", body: "Hold up people, here some new stuff from one our firm favourites here on medicinalsounds.com - BANKS. This time the the L.A. beauty has teamed up with yet another key player in electronic scene with Schlomo taking on production duty. Just one more legendary producer to add to the list of artists she’s worked with, and it’s another perfect match. Slow and pensive with echoing claps and deep bass set up the stage for BANKS’ mesmerising vocals. It’s yet another track to get us salivating at the thought of the forthcoming debut album expect later this year.", soundcloud: "https://soundcloud.com/banksbanksbanks/banks-brain-prod-by-shlohmo", created_at: DateTime.new(2014, 1, 31))

Post.create!(title: "ASTR – Operate", body: "Time for a bit of sexy synth pop, in the form of NYC duo ASTR and their debut single ‘Operate‘. I’ve been playing this tune on my travels, and smooth 80′s vibes always puts me a good mood. “Call me the Doctor” – seem apt for medicinalsounds.com. If you like this then their latest offering, ‘We Fall Down‘ is another 80′s inspired piece from the same vein. Or check out ‘The Drum Remix‘ for a slowed down, even more sultry version of the original.", soundcloud: "https://soundcloud.com/astrtv/astr-operate", created_at: DateTime.new(2014, 1, 27))

Post.create!(title: "Hey Now – London Grammar (Arty Remix)", body: "As mentioned in my previous post there’s a whole host of music I’ve been enjoying over the past few months that I want to get up on the site. So without further ado here’s one of those tracks. It’s an epic remix of Medicinal Sounds’ favourite, London Grammar, by the young Russian Arty. He takes their break through track ‘Hey Now’ and give a tasty reworking making it suitable for the big room. Arty keeps Hannah Reid’s sublime vocals shining through whist adding in deep bass and uplifting synths, all combined to make a really special remix. This tracks been doing the rounds since late last year, so may be old news to some, but hopefully will be a new treat for a few of you.", soundcloud: "https://www.youtube.com/watch?v=LglFEjlGM48", created_at: DateTime.new(2014, 1, 24))

Post.create!(title: "Embe – Welcome To My House Mix", body: "Apologies loyal followers. It has been all quiet on the Medicinal Sounds front for far too long. With the festivities of Yuletide and a trip to the USA, medicinalsounds.com was sadly neglected. But fear not, as with a new year comes new music and there’s a whole host of tracks that I’ve been listening to that need some love on the site. But back to business, as this post is *fanfare* the 100th post on medicinalsounds.com. So to celebrate here is a mix of my favourite House and Deep House tracks from the blog over the past year. It was recorded live, in one take with no post production editing, so some of the mixing isn’t as tight as I’d like it to be, but I hope you enjoy. Now I’ve finally got my set up working properly, there’ll be more mixes in the near future. Welcome to 2013. Welcome To My House Mix", soundcloud: "https://soundcloud.com/official-medicinal-sounds/house-deep-house-mix", created_at: DateTime.new(2014, 1, 23))

Post.create!(title: "Hackman – Change My Life", body: "The latest offering from Hackman is sounding real good. ‘Change My Life‘, is a chilled slice of  delicious house that has been getting a lot of plays from myself. The whole EP is beautifully crafted piece of work with deep bass lines balanced against uplifting melodies. If you like this, then check out the remix Hackman did for my friends Eli and Fur track ‘Nightmares‘.", soundcloud: "https://soundcloud.com/futureboogie/change-my-life-sd-192-01", created_at: DateTime.new(2013, 12, 7))

Post.create!(title: "Bonobo – First Fires Ft. Grey Reverend (Maya Jane Coles Remix)", body: "The supremely talented Maya Jane Coles has put her hand to Bonobo’s ‘First Fires‘. Taken from his  album ‘The North Borders’ Coles has put her usual intoxicating deep feel to the track. I can’t think of a remix that Maya has put out that I haven’t played to death, and I feel this one will be no exception. Beautifully deep and augmenting the original quality put down by Bono. Top work once again from both artists.", soundcloud: "https://soundcloud.com/mayajanecoles/bonobo-first-fires-feat-grey-1", created_at: DateTime.new(2013, 11, 21))

Post.create!(title: "Metronomy – I’m Aquarius", body: "Indie-dance producer Joe Mount, aka Metronomy is set to release his follow up to ‘The English Riviera‘ in the form of his new album ‘Love Letters‘. Taken from the LP is ‘I’m Aquarius’. It’s a stripped back steady number, which reminds me of Friendly Fire’s ‘Paris’ to a certain extent. Mount started his musical life as a drummer before moving into production, and the clean simple percussion is at the hear of this track. I’m told that you can access the track through the Night Sky mobile app, by locating the Aquarius constellation in the sky. I’ll be honest I haven’t checked if this is true, but free find out and let me know.", soundcloud: "https://soundcloud.com/kwabs/kwabs-last-stand", created_at: DateTime.new(2013, 11, 20))

Post.create!(title: "Kwabs – Land Stand", body: "Frequent flyers on medinalsounds.com will be aware of Kwabs from the post we did on his first single ‘Spirit Fade‘. That was back in April this year, and we’ve been waiting patiently for the follow up. Fortunately it doesn’t disappoint. It’s another mesmerising combination of rich vocals and slow, deep instrumentation, aided by man of the moment SOHN on production. It forms part of a forthcoming album that we’re all eagerly anticipating. Another epic and emotive offering from Kwabs.", soundcloud: "https://soundcloud.com/kwabs/kwabs-last-stand", created_at: DateTime.new(2013, 11, 12))