Post.create!(title: "James Blake – Life Round Here (Feat. Chance The Rapper)", body: "For those of you who have heard James Blakes‘ ‘Overgrown’ album, the track ‘Life Round Here’, will be old news. However Blake has teamed up with Chicago based Chance The Rapper (aka Chancelor Bennett ) to put a rework on it. True to form, Blake brings his trademark deep melodic yet striped back sounds, complete with dubstep undertones. Chance’s verse breaths fresh life into the track, and the paring seems to fit perfectly. The two have said they would be keen to work together again, so hopefully this is a preview of more to come. The atmospheric black and white video is well worth a watch. It’s directed by Nabil, who has gained respect for his recent work with Kanye West and Frank Ocean. He states that he like to bring juxtapositions to his work, which would explain the lowrider cruising through the English countryside.", soundcloud: "https://www.youtube.com/watch?v=5S6U_krabrk")

Post.create!(title: "Maribou State – Truths (Feat. Jimi Nxir)", body: "(Southern Fried) Maribou State have managed to fox me, in that after their ‘Praise You‘ remix, I was expecting ‘Moon Circles‘ to be their next release after hearing it on their WHP mix they put up on Soundcloud. But here we are a month later and instead we get ‘Truths‘ the title track from their forthcoming EP, complete with the elusive ‘Moon Circles‘. But lets not feel hard done by as this track is certainly no let down. It’s another typically chilled affair from the UK duo, featuring the vocals of Jimi Nxir. Slow steady percussion, twined with laid back guitar, sliding synths and even some strings thrown in there for good measure. The EP is due for release on 21st of October so I guess I’ll just have to wait until then to get ‘Truths‘ and ‘Moon Circles‘ in my library to play out.", soundcloud: "https://soundcloud.com/mariboustate/truths-feat-jimi-nxir")

Post.create!(title: "Fehrplay – Indigo", body: "(Pryda Friends) Fresh from his set a Tomorrow World last weekend here’s a preview of the sixth release for Fehrplay on the Pryda Friends label. ‘Indigo’ is another deliciously rich piece of progressive house, with a glorious break down which build up to an epic drop. Due for release on October 21st, but you can stream it here until then.", soundcloud: "https://soundcloud.com/fehrplay/fehrplay-indigo-pryda-friends")

Post.create!(title: "Louis M^ttrs – War With Heaven (Catching Flies Remix)", body: "(MTA Records) Hard day at work? We have the perfect tonic here at Medicinal Sounds courtesy of one our firm favourites , Catching Flies. This time he’s put his remixing skills to work on Louis M^tters’ first single from his new ‘Beachy Head‘ EP, ‘War With Heaven‘. As we’ve come to expect is another effortlessly put together remix that just floats along and helps to wash away the stress. You can watch the thought provoking cinematic video for the original track below. It was directed by the Cannes Film Festival award winning Josh Cole, who was also behind Rudimental’s epic ‘Not Giving In‘.", soundcloud: "https://soundcloud.com/catchingfliesmusic/louis-m-ttrs-war-with-heaven", youtube: "https://www.youtube.com/watch?v=Y1RLFoNm7sI")

Post.create!(title: "BANKS – This Is What It Feels Like", body: "(Goodyears) Lil Silva and Jamie Woon have joined forces to produce the latest single from L.A. based singer BANKS. It’s another deep down tempo affair and follows on perfectly from ‘Waiting Game‘, where she enlisted the help of SOHN. You can hear the dub step influence of Woon flowing through the heart of the track. In a relatively short career, BANKS has managed to put together an impressive collection of work joining up with a number of different producers, with tracks like ‘Warm Water’, getting 189,000 views in the first month of it being put online. I like BANKS’ attitude, who by her own admission doesn’t like using social media, but decided to let her fans get in contact by putting up a working mobile number on her Facebook page.", soundcloud: "https://soundcloud.com/banksbanksbanks/banks-this-is-what-it-feels")

Post.create!(title: "FKA Twigs – Papi Pacify", body: "Here’s the video for the latest single from London based FKA Twigs, ‘Papi Pacify’. Deep, dark and brooding, the video matches the mood of the music. It’s an unnerving video, caught somewhere between raw sexuality and aggression, making for rather unsettling viewing. The track was co-produced by Arca, who has gained notoriety recency for working with Kanye on his Yeezus album. His dark electronic influence runs deep in this one. I’m really liking this follow up to ‘Water Me‘, and I’m keen to see what’s next from Twigs.", youtube: "https://www.youtube.com/watch?v=OydK91JjFOw")

Post.create!(title: "The Beloved – Sweet Harmony", body: "Time for another ‘Classic Cut’. This time we go back to 1993 for the biggest single from British band The Beloved. It’s an uplifting synthpop classic complete with sax solo that will be sure to give you a warming sense of inner peace. Possibly. This track has a special memory for me as it was played as the last track at a warehouse rave in Nottingham at about 7am as the sun started to break through the gaps in the windows. Queue chills up the spine.", youtube: "https://www.youtube.com/watch?v=8-AcuIOFmIs")

Post.create!(title: "Steve Rachmad – Bling It Up!", body: "Here’s some laid back tech house to help you through a Monday. This track was released last year by Dutchman Steve Rachmad, and it passed me by until heard it at one of the Boiler Room sessions at Unknown Festival this year. It’s a warming little number, with clean beats, glowing bass and silky smooth synth melodies. I’ll admit I often find tech house a bit cold and soulless, but this is anything but. If the Autumn weather is getting you down, hit play on this one and imagine you’re on a sun drenched terrace in Europe somewhere.", youtube: "https://www.youtube.com/watch?v=HvINOZOn26M")

Post.create!(title: "HAIM – The Wire (Tourist Remix)", body: "(Polydor Records) It’s fair to say that Californian sister trio HAIM have gone from strength to strength since bursting onto scene last year. And with fame comes remixes. Some good, some bad. I’m pleased to say this reworking from Brighton boy Tourist falls into the ‘good’ category.  I first became of aware of Tourist with his 2012 release ‘Placid Acid‘, which got a good few play on my iTunes. His remix of ‘The Wire’ is another upbeat synthy number with filtered vocals that will be sure to get feet tapping. After rediscovering his work I look forward to new material from Tourist, be it original productions or remixes.", soundcloud: "https://soundcloud.com/touristmusic/haim-the-wire-tourist-remix")

Post.create!(title: "Anna Kendrick – Cups (Jellosea remix)", body: "Hello fellow music fans, apologies for the lack of post over the last two weeks. We had a team trip across Europe to Unknown Festival in Croatia. I’m sure any of you who where in attendance will agree that despite a few spots of rain it was a lot of fun. This track was a staple part of my traveling playlist, the Jellosea remix of Anna Kendrick’s single ‘Cups’. The Canadian producer has done a cracking job on this one, and it reminds me of the work of his fellow countryman, Cyril Hahn (who incidentally smashed his set at Unknown). Beautifully chilled house, perfect for a train journey from Hungary to Croatia.", soundcloud: "https://soundcloud.com/jellosea/anna-kendrick-cups-jellosea")

Post.create!(title: "Catching Flies & Ifan Dafydd – Don’t Know How", body: "(Push and Run) We’re big fans of Catching Flies here at MedicinalSounds.com, so it’s smiles all round when he puts out new material. This time he’s teamed up with Ifan Dafydd for his latest release “Don’t Know How”. It’s a typically laid back affair, with echoing clicks, tinkling piano and floating synths. The track samples the vocals of R&B star Lucy Pearl, and some of that soulful melody still plays through. It forms part of Push and Run’s ‘Tings in Boots’ Volume 2, but the track is available as a free download from his bandcamp page.", soundcloud: "https://soundcloud.com/catchingfliesmusic/catching-flies-ifan-dafydd-1")

Post.create!(title: "Bondax – Giving It All (Joe Goddard Remix)", body: "Sorry for the lack of posts of recent. As our Facebook page will tell you, we’ve been living it up in Ibiza followed directly by SW4 (admittedly ambitious). If like myself you are feeling a tad worse for wear after a weekend of SW4/ Notting Hill Carnival/ Creamfields then we have just the tonic. It comes in the form of a soul soothing remix by Joe Goddard of the Bondax track ‘Giving It All’. The original is great, and I’ve been watching the Bondax boys closely since catching their set at Glastonbury. Add in the remix abilities of Mr Goddard, who appears to have the midas touch, and you have cool late summer smash. Keep checking the Medicinalsounds Facebook page for more content from the aforementioned festivals – anyone else catch Boys Noize’s set?", soundcloud: "https://soundcloud.com/bondax/giving-it-all-joe-goddard")

Post.create!(title: "Martin Garrix – Animals", body: "Here at medicinalsounds.com we often have a slant towards the ambient, chilled out and deep side of electronic music. But every so often we like to mix up and bring you some good old fashioned ‘hand is the air, loose you shit’ kind of track. The kind of track you hear on a big sound system and say ‘Oh dear God, what is this?!’. This number from Dutch producer Martin Garrix is just that. ‘Animals’ was initially uploaded to the web with no artist causing a frenzy of speculation from bloggers and DJs as to who was responsible for this banger. Later it transpired that it was the young prodigy Garrix. Its a really mashup-in-one, and reminds me a bit of Porter Robison’s ‘Unison‘ in that respect. At points you could forgiven for mistakenly thinking it was Tiesto trace special, and then but 30 seconds later it goes dark and minimal enough to be a Dirtybird release. One thing is for sure, you can hear the dirty Dutch influence. I am fully aware that into their dance music will have heard this by now, but if not, well you’re in for a treat.", soundcloud: "https://soundcloud.com/martingarrix/martin-garrix-animals-original")

Post.create!(title: "Hayden James – Permission To Love (Charles Murdoch Remix)", body: "(Future Classic) Want more free music? You got it, this time from Charles Murdoch with his remix of Hayden James’ ‘Permission To Love’. Slow rolling, this track is somehow laid back and relaxed whist also sounding big and punchy at the same time. Top work from the Aussie lad. If you want to know a bit more about him have a read of the interview he did for DJmag.", soundcloud: "https://soundcloud.com/futureclassic/hayden-james-permission-to-6")

Post.create!(title: "Joel Compass – Astronaut (Ghost Loft Remix)", body: "(Black Butter) Here’s an appropriately spaced out remix of Joel Compass’s ‘Astronaut‘. The L.A based producer has only been making music for about a year as far as I can tell, and I can’t actually find much info about him online. However a quick listen to his Soundcloud pages shows this work is typical of his style. Warming, downtempo and smooth. Expect this to feature in one of my ‘Soul Ironing’ mixes soon. If you want something with a bit more bite, check out the Gorgon City Remix, for a deep house reworking. Due for forthcoming release on Black Butter Records, who are putting out so much good music at the moment. I recommend a look at their recent releases for a couple of gems.", soundcloud: "https://soundcloud.com/joel-compass/joel-compass-astronaut-ghost")