Post.create!(title: "Rosie Lowe – Right Thing", body: "(37 Adventures) Here’s some new music from an exciting new talent, Miss Rosie Lowe. The South London based singer has teamed up with Dave Okumu on production to create this number. Its starts of as a stripped back piano ballad, but soon descends into a tripped out etherial piece, not too far removed from some of James Blakes’ earlier work. There is real sense of familiarity when listening to this track, with similarities sure to be drawn to BANKS, but that’s not to take anything away from Rosie’s talent, and there are definitely worse be to be compared to. Looking forward to hearing new stuff from Rosie Lowe soon.", soundcloud: "https://soundcloud.com/rosielowe/rosie-lowe-right-thing", created_at: DateTime.new(2013, 11, 11))

Post.create!(title: "Laura Mvula – Sing To The Moon (Klangkarussell Remix)", body: "(Universal) After their feel good summer smash hit ‘Sonnentanz’, Klangkarussell turn their attention to Laura Mvula’s ‘Sing To The Moon’. The Austrian duo of Tobias Rieser and Adrian Held have taken the Laura’s original and kept things downtempo, whist giving it a smooth warm makeover. With an album currently being created, expect to hear a lot more from Klangkarussel in the near future.", soundcloud: "https://soundcloud.com/klangkarussell/sing-to-the-moon-laura-mvula", created_at: DateTime.new(2013, 11, 8))

Post.create!(title: "White Lies – Change (Dawn Golden Remix)", body: "Dawn Golden (aka Dexter Tortoriello) takes on the White Lies’ ode to heartbreak, ‘Change‘. Dawn Golden takes the track deeper, with a catchy melody and alluring synths; epic in every sense. Its another melancholy beautiful piece of work by  Tortiello, and with a full album set to drop early next year, expect to hear from this young man in the near future.", soundcloud: "https://soundcloud.com/dawn-golden/white-lies-change-dawn-golden", created_at: DateTime.new(2013, 11, 7))

Post.create!(title: "Mass Digital – Feel So Good", body: "(Audio Tonic) Serbian producer Mass Digital, aka Boris Mijolic is set to release his ‘Feel So Good‘ EP on 09/11/13 on Dubai’s Audio Tonic label. The title track of the same name is a slowed down tempo number with acid-tinged bass and entrancing melodies all set around solid drums. Mijolic has been steadily gaining moment in recent years with releases on Neurotraxx, Frequenza and Pacha Recordings. This EP is another statement of intent as Mijolic treads the melodic line between techno and house.", soundcloud: "https://soundcloud.com/official-medicinal-sounds/mass-digital-feel-so-good", created_at: DateTime.new(2013, 11, 6))

Post.create!(title: "Laura Welsh – Undiscovered (Blonde Remix)", body: "(Outsiders/ Polydor Records) Every so often I get a bit obsessed with a song. At the moment that is happening with the Blonde remix of Laura Welsh’s track ‘Undiscovered‘. It’s one of those delicious house reworks of an already beautiful track that just works. The Bristol based duo of Jake Manson and Adam Englefield have taken the chilled out original and given it a little house work over, with smooth bass line and upped tempo, all the while keeping Laura’s gorgeous vocals shining through. Sounding good.", soundcloud: "https://soundcloud.com/laurawelsh/laura-welsh-undiscovered", created_at: DateTime.new(2013, 11, 5))

Post.create!(title: "Moonbeam – Cocoon (Sunset Remix)", body: "Sorry for the lack of activity over the past week, been working some crazy hours to try and get some cash flow in. But back to the matter at hand. Time to add another tune into the ‘Classic Cuts‘ vault. This time its the Russian Khaleev brother’s Moonbeam who take their place, with the Sunset remix of their own track ‘Cocoon‘. It’s dreamy placid reworking as the title suggests, with the beat gently ebbing along before the high bubbling synths come in. This tune has such good memories for me – laying in a park, in the sunshine with a few beers and nothing to do for the rest of the day. Warming thoughts as the weather turns cold here in rainy old England.", soundcloud: "https://soundcloud.com/tune-of-the-week/moonbeam-cocoon-sunset-mix", created_at: DateTime.new(2013, 11, 4))

Post.create!(title: "Movement – Us", body: "(Modular) Sydney based trio, Movement, drop their second single ‘Us’. It’s a dark emotive affair and upon closer inspection the lyrics go a little deeper than a lot of other electronic artists around at the moment. The slowed tempo and almost whispered vocals remind me of Jai Paul’s ‘Jasmin‘, which to be fair, is no bad thing. I’ve been playing this to death for the past few weeks and it’s still sounding good.", soundcloud: "https://soundcloud.com/modularpeople/movement-us-1", created_at: DateTime.new(2013, 10, 22))

Post.create!(title: "Breach – Everything You Never Had (Joe Goddard Remix)", body: "(Atlantic Records) As you can probably tell, Medicinal Sounds is undergoing to bit of cosmetic work at the moment. But don’t worry while we give the site a lick of new paint we’ll continue to bring you great new music. As proof here’s the delicious Joe Goddard Remix of Breach’s ‘Everything You Never Had’. The original is the next release from Breach (aka Ben Westbeech) after his summer smash ‘Jack’. It takes a slightly more old school feel, with the soulful vocals of Andreya Triana. Breach has promised a full album release in 2013 which I’m sure many people are waiting for with bated breath. Now onto the remix, let’s be honest Mr Goddard seems to be able to do no wrong at the moment. He has well and truly established himself as one of the heavyweights in House music, whether it be as one half of the Two Bears, playing with Hot Chip, or just by himself as a producer. His take on ‘Everything You Never Had’ is another entry into a pretty flawless and extensive back catalogue. The memorising loop and bird sounds give a warming feeling of calm. Top quality work once again from the big man.", soundcloud: "https://soundcloud.com/breach-uk/everything-you-never-had-joe-goddard", created_at: DateTime.new(2013, 10, 19))

Post.create!(title: "Kyle Watson – Throwback (Black Loops Remix)", body: "Kyle Watson’s new ‘Throwback‘ EP is due for release on 28th October this year. The South African has been rising up the ranks over the past few years, working with various labels before releasing this EP on Gruuv. He brings his trademark rugged house sound to the outfit that will be sure to fit in perfectly. ‘Throwback‘ is comprised of three original tracks and one remix from the Italian born, Berlin based duo Black Loops.  Gruuv’s newest signing put their own spin on ‘Throwback’, giving it a more dubbed out, deeper feel.", soundcloud: "https://soundcloud.com/gruuv/kyle-watson-throwback-black", created_at: DateTime.new(2013, 10, 15))

Post.create!(title: "James Blake – Life Round Here (Feat. Chance The Rapper)", body: "For those of you who have heard James Blakes‘ ‘Overgrown’ album, the track ‘Life Round Here’, will be old news. However Blake has teamed up with Chicago based Chance The Rapper (aka Chancelor Bennett ) to put a rework on it. True to form, Blake brings his trademark deep melodic yet striped back sounds, complete with dubstep undertones. Chance’s verse breaths fresh life into the track, and the paring seems to fit perfectly. The two have said they would be keen to work together again, so hopefully this is a preview of more to come. The atmospheric black and white video is well worth a watch. It’s directed by Nabil, who has gained respect for his recent work with Kanye West and Frank Ocean. He states that he like to bring juxtapositions to his work, which would explain the lowrider cruising through the English countryside.", soundcloud: "https://www.youtube.com/watch?v=5S6U_krabrk", created_at: DateTime.new(2013, 10, 14))