Post.create!(title: "Shigeto – What U Really Needed", body: "The only thing better than finding a great new tune, is finding a great new tune that the producer is giving away for free. And that’s exactly what we have here from Shigeto. A beautiful, winding, other worldly piece of ambient house. It features the vocals of Brandon Mitchell and Carlos Garcia, and is perfect if you’re looking to unwind after a hectic day. Get hold of copy from Detroit man’s Soundcloud page without fear of any pesky copyright layers knocking on your door. But then all of our readers get their music by legal means anyway...", soundcloud: "https://soundcloud.com/shigeto/what-u-really-needed-ft")

Post.create!(title: "Burial – Archangel", body: "(Hyperdub) It’s time to add another selection to our ‘Classic Cuts‘. This time we give up the position to the enigmatic Burial. Despite critical acclaim for both of his first two albums as well as a mercury music nomination, little was known about the man from South London. In 2008 he posted a picture of himself on his Myspace and dispelled rumours of Norman Cook or Richard D James being behind the music. It was in fact Mr William Bevan, and he explained that he was a “lowkey guy” who “just wanted to make some tunes”. And so he has. This track is just one classic of many in his collection.  If this is the only single of his you’ve heard, I strongly urge you to go through his back catalogue. ‘Archangel’ is taken from his 2007 album ‘Untrue’. I appreciate that it’s highly unlikely that this will be the first time anyone has head this tune, however I hope that it will remind you just how good it is. A fitting soundtrack to the recent weather change.")

Post.create!(title: "Boynextdoor – The Magical Mystery Tour", body: "My good friend and coworker Dan Bendal, aka Boynextdoor has just put the finishing touches on this upbeat electro house number. He informs me that it was started 3 years ago, but he’s only just come back, reworked it and it’s now ready for the the world to hear. Dan is qualified doctor, so his track makes a fitting addition to medicinalsounds.com. He’s also giving this track away free on his Soundcloud page. I just hope we’re not waiting 3 years for the next one Dan.", soundcloud: "https://soundcloud.com/boynextdoor/boynextdoor-the-magical")

Post.create!(title: "Phaeleh – Storm (Ft. Jess Mills)", body: "Fancy a bit of deep moody dubstep? Well you’re in luck. It comes in the form of Bristol based producer Phaeleh, and features the vocal talents of young Jess Mills. The name may be familiar if you like your dubstep as she was the vocalist for Breakage’s ‘Fighting Fire‘, and has had her singles remixed by various DJ’s, including Phaeleh himself on her track ‘For My Sins‘. The video is a tad ’90′s cliche, but we’re all here for the music and not girls in short shorts. Right?", soundcloud: "https://www.youtube.com/watch?v=rt3C85D7cY8")

Post.create!(title: "Eli & Fur – You’re So High", body: "Here’s the lead track off the new EP from my good friends Eli & Fur. It’s another tantalisingly melodic house number. Smooth and silky on the ears with just enough bite from bass running beneath. This will be sure to get some heads nodding this summer. The EP is due for release on the 22nd July, available on beatport. If you like this; check out their track ‘Nightmares‘, complete with it’s own Hackman remix.", soundcloud: "https://soundcloud.com/eliandfur/youre-so-high")

Post.create!(title: "Fehrplay – Talk To Me", body: "(Pryda Friends) Here’s the new one from Fehrplay, ‘Talk To Me‘. Having steadily built his reputation to become one of the key players in house music, Fehrplay comes good once again. I’ve been meaning to put one of his tracks up on the site for a while, but just haven’t got round to it until now. A slightly more tech sound than his previous work, it reminds me a bit of Scuba’s recent stuff, but with it’s own unique twist. My good friend Kid Booka put me onto this young Norweigen a while ago and his whole back catalogue is well worth checking out. To be released on the Scandinavian rich ‘Prydra Friends’ label on 29th of July.")

Post.create!(title: "Kidnap Kid – Survive", body: "(Black Butter Records) I’ve been aware of Kidnap Kid aka Matt Relton for a while now, but haven’t been blown away by his work to date. Don’t get me wrong; I don’t hate it (and you don’t become iTunes ‘Best Electronic Song of 2012′ as he did with ‘Vehl’ without some serious talent), I just felt his tunes were lacking something. And I think this track has found that something. ‘Survive’ is 7 minute 30 second piece of beautifully crafted deep house. The off beat lick, the soulful vocals, the uplifting melodies, the deep rolling bass – all the elements perfectly combined to make a delicious piece of house music. Congratulations Mr Relton; you’ve just gained a new fan.", soundcloud: "https://soundcloud.com/kidnap_kid/survive")

Post.create!(title: "Dusky – Mr Man", body: "I know, I know, yet another post about Dusky!? Well I’m afraid so good readers. And after seeing them at Glastonbury and then hearing this new track and can assue you it’s a case of credit where credit is due. This latest offering from the duo is sublime once again. The warming bass line giving way to a sparse and haunting piano breakdown, before slowing bringing in the snare and building the track back up. Deep glowing house music from one of my favorite producer duo’s around. Due for release as part of Anjunadeep 05 on 27/07/13.", soundcloud: "https://soundcloud.com/duskymusic/dusky-mr-man")

Post.create!(title: "J.Rabbit – Tequila Remix", body: "(Spinnin’ Records) Hello ladies and gents, apologies for the lack of posts over the last week or so. I like about 100,000 other music lovers was at Glastonbury. If you weren’t lucky enough to get a ticket we’ve added some content to our Facebook page to give you a very small taste of what went on. While you’re there why not give us a ‘Like’. Anyway back to business, whist stumbling around in a drunken haze on Saturday morning on the way back to my camp site, I came across a little stage playing a heady mix of house, dubstep, trap and disco. I have no idea who the DJ was but he dropped this ‘Tequila’ trap remix and it went off.  So here it is for all to enjoy.", soundcloud: "https://soundcloud.com/jrabbit/j-rabbit-tequila-remix-free")

Post.create!(title: "Catching Flies – The Long Journey Home EP", body: "(Indigo Soul) Catching Flies latest EP, ‘The Long Journey Home’ is simply sublime. The 22 year old made a big impression with his first EP ‘The Stars’ last year. This follow up is top quality, down tempo music, with all three tracks delivering the goods. The two remix aren’t half bad either. Available now, get hold of a copy and see for yourself.", soundcloud: "https://soundcloud.com/catchingfliesmusic/the-long-journey-home")

Post.create!(title: "Catching Flies – Grey Skies", soundcloud: "https://soundcloud.com/catchingfliesmusic/grey-skies")

Post.create!(title: "Catching Flies - Stay Forever", soundcloud: "https://soundcloud.com/catchingfliesmusic/stay-forever")

Post.create!(title: "Disclosure – You & Me (Flume Remix)", body: "Disclosure really are flying high right now. Headlining festivals, curating an upcoming Warehouse project and a number one album to boot. As a result its hardly surprising that they’re THE act to remix at the moment. I was sold hook, line and sinker on the Baauer Remix of ‘You & Me‘, but this reworking from Australian producer Flume has given me food for thought. Less frantic in it’s nature, the track takes on a more glich hop style, that works really nicely. I eagerly await more from Flume in the near future.", soundcloud: "https://soundcloud.com/flume/disclosure-you-me-flume-remix")