Post.create!(title: "Booka Shade – In White Rooms", body: "(Get Physical Music) Every 10th post here on Medicinal Sounds we like add to our ‘Classic Cuts‘ section. So here to join those already in the hall of fame is Booka Shade with ‘In White Rooms‘. The German house duo is comprised of Walter Merziger and Arno Kammermeier. They’ve been described as veterans of the German electronic music scene, and are renowned for their visually impressive shows; wowing audiences with percussion and re workings live on stage. This is a gorgeously simple track that slowly builds in intensity, never quite reaching the frantic crescendo that much of todays producers do; but that in itself is part of the charm. For me this was the standout track on their ‘Movements’ album, but if you want something something  a bit more jacking, have a listen to ‘Blue Rooms‘ for a techier reworking. Originally released back in May 2006 it sounds as good today as it did then. If you like this check out ‘Mandarine Girl‘, ‘Body Language‘, or any of the rest of their back catalogue.", soundcloud: "https://soundcloud.com/olyspirit/in-white-rooms-booka-shade-original-mix")

Post.create!(title: "Kings Of Leon – Closer (No One 32 Remix)", body: "Here’s a nice little remix of my favorite Kings Of Leon track ‘Closer’, courtesy of No One 32. I can’t find out much about this German DJ/ producer, other than his real name, Andreas Leitel, on his Soundcloud page. It puts a nice deep house spin on the track whist keeping Caleb Followill’s emotional vocals at the heart of the tune.", soundcloud: "https://soundcloud.com/no-one-32/closer-no-one-32-vocal-rmx")

Post.create!(title: "Close Feat. Joe Dukie – My Way (Dusky Remix)", body: "It’s two for two with Dusky here on medicinalsounds.com, with two mentions in as many posts. This time they take on Will Saul’s alias – Close. They give the melodic deep house treatment to his second single ‘My Way’, taken from forthcoming album ‘Get Closer’. Just further proof of Dusky’s ability and intent. Smooth deep house vibes, whilst keeping Joe Dukie’s vocals (of Fatt Freddie’s Drop) clean and true. Sounding good on a sunny evening.", soundcloud: "https://soundcloud.com/duskymusic/my-way-dusky-remix")

Post.create!(title: "Dusky – Vanishing Point", body: "(Naked Naked) Here’s the latest single from Dusky, the London based duo comprised of Alfie Granger-Howell and Nick Harriman. Formerly known as Solarity, the pair may have changed their name but are still producing their distinctive rich melodic sound. This track is no exception with it’s warm deep bass line and steady hi-hat ticking through this is sure to have the dance floors moving. It froms part of their forthcoming EP of the same name, due for release on 03/06/13. You can stream a preview on their Soundclound page now. If you like this check out their remix of Justin Martin’s ‘Don’t Go‘.", soundcloud: "https://soundcloud.com/duskymusic/vanishing-point")

Post.create!(title: "Fatboyslim – Praise You (Maribou State Remix)", body: "(Skint Records) It takes a brave individual to take on a stone cold classic like Norman Cook’s ‘Praise You’. In this case it took two, in the form of Maribou State. I first heard of this duo on their collaboration with Pedestrian – ‘Mask‘. This reworking is an equally ambient and floating affair to start with before adding in those classic vocals and slowly building up the energy. It appears fortune does indeed favour the brave. Available for download on Beatport now.", soundcloud: "https://soundcloud.com/fatboyslim/fatboy-slim-praise-you-maribou")

Post.create!(title: "Disclosure – When A Fire Starts To Burn", body: "(PMR Records) It’s fair to say the Disclosure boys are gaining rather a large fan base. With their album still unreleased, they managed to get over 40,000 plays of this track in the first hour of uploading it to their soundcloud! ‘When A Fire Starts To Burn’ is the latest track to be previewed from the Lawrence brothers’ ‘Settle’ album due for release on 03/06/13. Apparently the boys found the sample for the track by typing “motivational speaker Harlem” into iTunes. The aim to was to collaborate with a rapper, but I feel this sample has worked out rather well instead. The tune is slightly more minimal take on the melodic house they’ve become renowned for. If you manage to get hold of tickets to their secret album launch party, feel free to invite us.", soundcloud: "https://soundcloud.com/disclosuremusic/when-a-fire-starts-to-burn")

Post.create!(title: "Retrograde (Finn Pilly Edit)", body: "Here’s a cracking edit of James Blake’s ‘Retrograde’ by Finn Pilly, a.k.a. Finnebassen. I’ve been a fan of this Norwegian since hearing ‘Touching Me‘ for the first time in Ibiza last year. Since then releases including ‘Such A High‘, ‘If You Only Knew‘ and his cover of Prince’s ‘When Doves Cry‘ have made him one of my favorite downtempo producers. Here he takes the originally sobre ‘Retrograde’ and turns it into a sexy deep house classic, all the while maintaining Blake’s sublime vocals. You can download a copy for free from his Soundcloud. Happy Days.", soundcloud: "https://soundcloud.com/finnebassen/retrograde-finn-pilly-edit")

Post.create!(title: "Hervé – Lose Control (feat. Seasfire)", body: "This track passed me by when it was released, but I’m glad a stumbled across it on Herve’s soundcloud. It’s a mesmerising, floating piece of music from the head of ‘Cheap Thrills label’. Taken from the album ‘The Art Of Disappearing’ which also features guest performances from Katie Stelmanis of Austra, Maria Minerva and Niki & The Dove. It’s out now so go and get hold of a copy.", soundcloud: "https://soundcloud.com/hervespace/herve-lose-control")

Post.create!(title: "Disclosure – You & Me ft. Eliza Doolittle (Baauer Remix)", body: "He’s at it again. This time Baauer has taken on the British brothers, Disclosure, and their latest offering featuring Eliza Doolittle. Like so many of the good new tunes emerging at the moment this was previewed at Coachella and has now made its way onto the web for all to enjoy. Following the success of his remix of AlunaGeorge’s ‘Attracting Flies‘, Baauer has decided rework another of the UK’s hottest electronic acts in Disclosure. He pushes up the tempo, shifts the pitch on the vocals and adds a sprinkling of his trademark Trap style to tie it all together. Slightly different sound here from Baauer, and I like it. A lot. Available for download on 21st of May. Stream it here until then. If you’re after something a bit funkier, check out the original version below. Warming garage vibes.", soundcloud: "https://soundcloud.com/baauer/disclosure-you-me-ft-eliza", youtube: "https://www.youtube.com/watch?v=W_vM8ePGuRM")

Post.create!(title: "Raffertie – Benediction", body: "Stirring cover from Raffertie of Hot Natured’s ‘Benediction’. The British boss of micro label ‘Super Recordings’ puts a deeper twist on one of last years summer smashes. With a deep kick drum at the heart of the track and smooth vocals, this is a effortlessly cool tune. You can download the track for free from the Mixmag soundcloud page. What a treat.", soundcloud: "https://soundcloud.com/mixmag-1/free-mp3-raffertie-benediction")

Post.create!(title: "Claude VonStroke – Who’s Afraid of Detroit?", body: "(Dirtybird Records) It’s official, Medicinalsounds.com is 50 post deep. And to celebrate our 50th is a proper ‘Classic Cut’. It comes from head honcho at Dirtybird, Calude VonStroke and his classic track ‘Who’s Afraid Of Detroit?’. Deep dark Detroit techo at it’s finest. Released back in November 2006, it sounds as good today as it it did then. Hit play and remind yourself how good this one is...", soundcloud: "https://soundcloud.com/claudevonstroke/whos-afraid-of-detroit-db005")