Post.create!(title: "Bondax – Giving It All (Joe Goddard Remix)", body: "Sorry for the lack of posts of recent. As our Facebook page will tell you, we’ve been living it up in Ibiza followed directly by SW4 (admittedly ambitious). If like myself you are feeling a tad worse for wear after a weekend of SW4/ Notting Hill Carnival/ Creamfields then we have just the tonic. It comes in the form of a soul soothing remix by Joe Goddard of the Bondax track ‘Giving It All’. The original is great, and I’ve been watching the Bondax boys closely since catching their set at Glastonbury. Add in the remix abilities of Mr Goddard, who appears to have the midas touch, and you have cool late summer smash. Keep checking the Medicinalsounds Facebook page for more content from the aforementioned festivals – anyone else catch Boys Noize’s set?", soundcloud: "https://soundcloud.com/bondax/giving-it-all-joe-goddard", created_at: DateTime.new(2013, 8, 27))

Post.create!(title: "Martin Garrix – Animals", body: "Here at medicinalsounds.com we often have a slant towards the ambient, chilled out and deep side of electronic music. But every so often we like to mix up and bring you some good old fashioned ‘hand is the air, loose you shit’ kind of track. The kind of track you hear on a big sound system and say ‘Oh dear God, what is this?!’. This number from Dutch producer Martin Garrix is just that. ‘Animals’ was initially uploaded to the web with no artist causing a frenzy of speculation from bloggers and DJs as to who was responsible for this banger. Later it transpired that it was the young prodigy Garrix. Its a really mashup-in-one, and reminds me a bit of Porter Robison’s ‘Unison‘ in that respect. At points you could forgiven for mistakenly thinking it was Tiesto trace special, and then but 30 seconds later it goes dark and minimal enough to be a Dirtybird release. One thing is for sure, you can hear the dirty Dutch influence. I am fully aware that into their dance music will have heard this by now, but if not, well you’re in for a treat.", soundcloud: "https://soundcloud.com/martingarrix/martin-garrix-animals-original", created_at: DateTime.new(2013, 8, 18))

Post.create!(title: "Hayden James – Permission To Love (Charles Murdoch Remix)", body: "(Future Classic) Want more free music? You got it, this time from Charles Murdoch with his remix of Hayden James’ ‘Permission To Love’. Slow rolling, this track is somehow laid back and relaxed whist also sounding big and punchy at the same time. Top work from the Aussie lad. If you want to know a bit more about him have a read of the interview he did for DJmag.", soundcloud: "https://soundcloud.com/futureclassic/hayden-james-permission-to-6", created_at: DateTime.new(2013, 8, 9))

Post.create!(title: "Joel Compass – Astronaut (Ghost Loft Remix)", body: "(Black Butter) Here’s an appropriately spaced out remix of Joel Compass’s ‘Astronaut‘. The L.A based producer has only been making music for about a year as far as I can tell, and I can’t actually find much info about him online. However a quick listen to his Soundcloud pages shows this work is typical of his style. Warming, downtempo and smooth. Expect this to feature in one of my ‘Soul Ironing’ mixes soon. If you want something with a bit more bite, check out the Gorgon City Remix, for a deep house reworking. Due for forthcoming release on Black Butter Records, who are putting out so much good music at the moment. I recommend a look at their recent releases for a couple of gems.", soundcloud: "https://soundcloud.com/joel-compass/joel-compass-astronaut-ghost", created_at: DateTime.new(2013, 8, 7))

Post.create!(title: "Shigeto – What U Really Needed", body: "The only thing better than finding a great new tune, is finding a great new tune that the producer is giving away for free. And that’s exactly what we have here from Shigeto. A beautiful, winding, other worldly piece of ambient house. It features the vocals of Brandon Mitchell and Carlos Garcia, and is perfect if you’re looking to unwind after a hectic day. Get hold of copy from Detroit man’s Soundcloud page without fear of any pesky copyright layers knocking on your door. But then all of our readers get their music by legal means anyway...", soundcloud: "https://soundcloud.com/shigeto/what-u-really-needed-ft", created_at: DateTime.new(2013, 7, 31))

Post.create!(title: "Burial – Archangel", body: "(Hyperdub) It’s time to add another selection to our ‘Classic Cuts‘. This time we give up the position to the enigmatic Burial. Despite critical acclaim for both of his first two albums as well as a mercury music nomination, little was known about the man from South London. In 2008 he posted a picture of himself on his Myspace and dispelled rumours of Norman Cook or Richard D James being behind the music. It was in fact Mr William Bevan, and he explained that he was a “lowkey guy” who “just wanted to make some tunes”. And so he has. This track is just one classic of many in his collection.  If this is the only single of his you’ve heard, I strongly urge you to go through his back catalogue. ‘Archangel’ is taken from his 2007 album ‘Untrue’. I appreciate that it’s highly unlikely that this will be the first time anyone has head this tune, however I hope that it will remind you just how good it is. A fitting soundtrack to the recent weather change.", created_at: DateTime.new(2013, 7, 30))

Post.create!(title: "Boynextdoor – The Magical Mystery Tour", body: "My good friend and coworker Dan Bendal, aka Boynextdoor has just put the finishing touches on this upbeat electro house number. He informs me that it was started 3 years ago, but he’s only just come back, reworked it and it’s now ready for the the world to hear. Dan is qualified doctor, so his track makes a fitting addition to medicinalsounds.com. He’s also giving this track away free on his Soundcloud page. I just hope we’re not waiting 3 years for the next one Dan.", soundcloud: "https://soundcloud.com/boynextdoor/boynextdoor-the-magical", created_at: DateTime.new(2013, 7, 29))

Post.create!(title: "Phaeleh – Storm (Ft. Jess Mills)", body: "Fancy a bit of deep moody dubstep? Well you’re in luck. It comes in the form of Bristol based producer Phaeleh, and features the vocal talents of young Jess Mills. The name may be familiar if you like your dubstep as she was the vocalist for Breakage’s ‘Fighting Fire‘, and has had her singles remixed by various DJ’s, including Phaeleh himself on her track ‘For My Sins‘. The video is a tad ’90′s cliche, but we’re all here for the music and not girls in short shorts. Right?", soundcloud: "https://www.youtube.com/watch?v=rt3C85D7cY8", created_at: DateTime.new(2013, 7, 22))

Post.create!(title: "Eli & Fur – You’re So High", body: "Here’s the lead track off the new EP from my good friends Eli & Fur. It’s another tantalisingly melodic house number. Smooth and silky on the ears with just enough bite from bass running beneath. This will be sure to get some heads nodding this summer. The EP is due for release on the 22nd July, available on beatport. If you like this; check out their track ‘Nightmares‘, complete with it’s own Hackman remix.", soundcloud: "https://soundcloud.com/eliandfur/youre-so-high", created_at: DateTime.new(2013, 7, 18))

Post.create!(title: "Fehrplay – Talk To Me", body: "(Pryda Friends) Here’s the new one from Fehrplay, ‘Talk To Me‘. Having steadily built his reputation to become one of the key players in house music, Fehrplay comes good once again. I’ve been meaning to put one of his tracks up on the site for a while, but just haven’t got round to it until now. A slightly more tech sound than his previous work, it reminds me a bit of Scuba’s recent stuff, but with it’s own unique twist. My good friend Kid Booka put me onto this young Norweigen a while ago and his whole back catalogue is well worth checking out. To be released on the Scandinavian rich ‘Prydra Friends’ label on 29th of July.", created_at: DateTime.new(2013, 7, 16))