Post.create!(title: "Kidnap Kid – Survive", body: "(Black Butter Records) I’ve been aware of Kidnap Kid aka Matt Relton for a while now, but haven’t been blown away by his work to date. Don’t get me wrong; I don’t hate it (and you don’t become iTunes ‘Best Electronic Song of 2012′ as he did with ‘Vehl’ without some serious talent), I just felt his tunes were lacking something. And I think this track has found that something. ‘Survive’ is 7 minute 30 second piece of beautifully crafted deep house. The off beat lick, the soulful vocals, the uplifting melodies, the deep rolling bass – all the elements perfectly combined to make a delicious piece of house music. Congratulations Mr Relton; you’ve just gained a new fan.", soundcloud: "https://soundcloud.com/kidnap_kid/survive", created_at: DateTime.new(2013, 7, 14))

Post.create!(title: "Dusky – Mr Man", body: "I know, I know, yet another post about Dusky!? Well I’m afraid so good readers. And after seeing them at Glastonbury and then hearing this new track and can assue you it’s a case of credit where credit is due. This latest offering from the duo is sublime once again. The warming bass line giving way to a sparse and haunting piano breakdown, before slowing bringing in the snare and building the track back up. Deep glowing house music from one of my favorite producer duo’s around. Due for release as part of Anjunadeep 05 on 27/07/13.", soundcloud: "https://soundcloud.com/duskymusic/dusky-mr-man", created_at: DateTime.new(2013, 7, 10))

Post.create!(title: "J.Rabbit – Tequila Remix", body: "(Spinnin’ Records) Hello ladies and gents, apologies for the lack of posts over the last week or so. I like about 100,000 other music lovers was at Glastonbury. If you weren’t lucky enough to get a ticket we’ve added some content to our Facebook page to give you a very small taste of what went on. While you’re there why not give us a ‘Like’. Anyway back to business, whist stumbling around in a drunken haze on Saturday morning on the way back to my camp site, I came across a little stage playing a heady mix of house, dubstep, trap and disco. I have no idea who the DJ was but he dropped this ‘Tequila’ trap remix and it went off.  So here it is for all to enjoy.", soundcloud: "https://soundcloud.com/jrabbit/j-rabbit-tequila-remix-free", created_at: DateTime.new(2013, , ))

Post.create!(title: "Catching Flies – The Long Journey Home EP", body: "(Indigo Soul) Catching Flies latest EP, ‘The Long Journey Home’ is simply sublime. The 22 year old made a big impression with his first EP ‘The Stars’ last year. This follow up is top quality, down tempo music, with all three tracks delivering the goods. The two remix aren’t half bad either. Available now, get hold of a copy and see for yourself.", soundcloud: "https://soundcloud.com/catchingfliesmusic/the-long-journey-home", created_at: DateTime.new(2013, , ))

Post.create!(title: "Catching Flies – Grey Skies", soundcloud: "https://soundcloud.com/catchingfliesmusic/grey-skies", created_at: DateTime.new(2013, , ))

Post.create!(title: "Catching Flies - Stay Forever", soundcloud: "https://soundcloud.com/catchingfliesmusic/stay-forever", created_at: DateTime.new(2013, , ))

Post.create!(title: "Disclosure – You & Me (Flume Remix)", body: "Disclosure really are flying high right now. Headlining festivals, curating an upcoming Warehouse project and a number one album to boot. As a result its hardly surprising that they’re THE act to remix at the moment. I was sold hook, line and sinker on the Baauer Remix of ‘You & Me‘, but this reworking from Australian producer Flume has given me food for thought. Less frantic in it’s nature, the track takes on a more glich hop style, that works really nicely. I eagerly await more from Flume in the near future.", soundcloud: "https://soundcloud.com/flume/disclosure-you-me-flume-remix", created_at: DateTime.new(2013, , ))

Post.create!(title: "Booka Shade – In White Rooms", body: "(Get Physical Music) Every 10th post here on Medicinal Sounds we like add to our ‘Classic Cuts‘ section. So here to join those already in the hall of fame is Booka Shade with ‘In White Rooms‘. The German house duo is comprised of Walter Merziger and Arno Kammermeier. They’ve been described as veterans of the German electronic music scene, and are renowned for their visually impressive shows; wowing audiences with percussion and re workings live on stage. This is a gorgeously simple track that slowly builds in intensity, never quite reaching the frantic crescendo that much of todays producers do; but that in itself is part of the charm. For me this was the standout track on their ‘Movements’ album, but if you want something something  a bit more jacking, have a listen to ‘Blue Rooms‘ for a techier reworking. Originally released back in May 2006 it sounds as good today as it did then. If you like this check out ‘Mandarine Girl‘, ‘Body Language‘, or any of the rest of their back catalogue.", soundcloud: "https://soundcloud.com/olyspirit/in-white-rooms-booka-shade-original-mix", created_at: DateTime.new(2013, , ))

Post.create!(title: "Kings Of Leon – Closer (No One 32 Remix)", body: "Here’s a nice little remix of my favorite Kings Of Leon track ‘Closer’, courtesy of No One 32. I can’t find out much about this German DJ/ producer, other than his real name, Andreas Leitel, on his Soundcloud page. It puts a nice deep house spin on the track whist keeping Caleb Followill’s emotional vocals at the heart of the tune.", soundcloud: "https://soundcloud.com/no-one-32/closer-no-one-32-vocal-rmx", created_at: DateTime.new(2013, , ))

Post.create!(title: "Close Feat. Joe Dukie – My Way (Dusky Remix)", body: "It’s two for two with Dusky here on medicinalsounds.com, with two mentions in as many posts. This time they take on Will Saul’s alias – Close. They give the melodic deep house treatment to his second single ‘My Way’, taken from forthcoming album ‘Get Closer’. Just further proof of Dusky’s ability and intent. Smooth deep house vibes, whilst keeping Joe Dukie’s vocals (of Fatt Freddie’s Drop) clean and true. Sounding good on a sunny evening.", soundcloud: "https://soundcloud.com/duskymusic/my-way-dusky-remix", created_at: DateTime.new(2013, , ))

Post.create!(title: "Dusky – Vanishing Point", body: "(Naked Naked) Here’s the latest single from Dusky, the London based duo comprised of Alfie Granger-Howell and Nick Harriman. Formerly known as Solarity, the pair may have changed their name but are still producing their distinctive rich melodic sound. This track is no exception with it’s warm deep bass line and steady hi-hat ticking through this is sure to have the dance floors moving. It froms part of their forthcoming EP of the same name, due for release on 03/06/13. You can stream a preview on their Soundclound page now. If you like this check out their remix of Justin Martin’s ‘Don’t Go‘.", soundcloud: "https://soundcloud.com/duskymusic/vanishing-point", created_at: DateTime.new(2013, , ))

Post.create!(title: "Fatboyslim – Praise You (Maribou State Remix)", body: "(Skint Records) It takes a brave individual to take on a stone cold classic like Norman Cook’s ‘Praise You’. In this case it took two, in the form of Maribou State. I first heard of this duo on their collaboration with Pedestrian – ‘Mask‘. This reworking is an equally ambient and floating affair to start with before adding in those classic vocals and slowly building up the energy. It appears fortune does indeed favour the brave. Available for download on Beatport now.", soundcloud: "https://soundcloud.com/fatboyslim/fatboy-slim-praise-you-maribou", created_at: DateTime.new(2013, , ))

Post.create!(title: "Disclosure – When A Fire Starts To Burn", body: "(PMR Records) It’s fair to say the Disclosure boys are gaining rather a large fan base. With their album still unreleased, they managed to get over 40,000 plays of this track in the first hour of uploading it to their soundcloud! ‘When A Fire Starts To Burn’ is the latest track to be previewed from the Lawrence brothers’ ‘Settle’ album due for release on 03/06/13. Apparently the boys found the sample for the track by typing “motivational speaker Harlem” into iTunes. The aim to was to collaborate with a rapper, but I feel this sample has worked out rather well instead. The tune is slightly more minimal take on the melodic house they’ve become renowned for. If you manage to get hold of tickets to their secret album launch party, feel free to invite us.", soundcloud: "https://soundcloud.com/disclosuremusic/when-a-fire-starts-to-burn", created_at: DateTime.new(2013, , ))

Post.create!(title: "Retrograde (Finn Pilly Edit)", body: "Here’s a cracking edit of James Blake’s ‘Retrograde’ by Finn Pilly, a.k.a. Finnebassen. I’ve been a fan of this Norwegian since hearing ‘Touching Me‘ for the first time in Ibiza last year. Since then releases including ‘Such A High‘, ‘If You Only Knew‘ and his cover of Prince’s ‘When Doves Cry‘ have made him one of my favorite downtempo producers. Here he takes the originally sobre ‘Retrograde’ and turns it into a sexy deep house classic, all the while maintaining Blake’s sublime vocals. You can download a copy for free from his Soundcloud. Happy Days.", soundcloud: "https://soundcloud.com/finnebassen/retrograde-finn-pilly-edit", created_at: DateTime.new(2013, , ))

Post.create!(title: "Hervé – Lose Control (feat. Seasfire)", body: "This track passed me by when it was released, but I’m glad a stumbled across it on Herve’s soundcloud. It’s a mesmerising, floating piece of music from the head of ‘Cheap Thrills label’. Taken from the album ‘The Art Of Disappearing’ which also features guest performances from Katie Stelmanis of Austra, Maria Minerva and Niki & The Dove. It’s out now so go and get hold of a copy.", soundcloud: "https://soundcloud.com/hervespace/herve-lose-control", created_at: DateTime.new(2013, , ))

Post.create!(title: "Disclosure – You & Me ft. Eliza Doolittle (Baauer Remix)", body: "He’s at it again. This time Baauer has taken on the British brothers, Disclosure, and their latest offering featuring Eliza Doolittle. Like so many of the good new tunes emerging at the moment this was previewed at Coachella and has now made its way onto the web for all to enjoy. Following the success of his remix of AlunaGeorge’s ‘Attracting Flies‘, Baauer has decided rework another of the UK’s hottest electronic acts in Disclosure. He pushes up the tempo, shifts the pitch on the vocals and adds a sprinkling of his trademark Trap style to tie it all together. Slightly different sound here from Baauer, and I like it. A lot. Available for download on 21st of May. Stream it here until then. If you’re after something a bit funkier, check out the original version below. Warming garage vibes.", soundcloud: "https://soundcloud.com/baauer/disclosure-you-me-ft-eliza", youtube: "https://www.youtube.com/watch?v=W_vM8ePGuRM", created_at: DateTime.new(2013, , ))

Post.create!(title: "Raffertie – Benediction", body: "Stirring cover from Raffertie of Hot Natured’s ‘Benediction’. The British boss of micro label ‘Super Recordings’ puts a deeper twist on one of last years summer smashes. With a deep kick drum at the heart of the track and smooth vocals, this is a effortlessly cool tune. You can download the track for free from the Mixmag soundcloud page. What a treat.", soundcloud: "https://soundcloud.com/mixmag-1/free-mp3-raffertie-benediction", created_at: DateTime.new(2013, , ))

Post.create!(title: "Claude VonStroke – Who’s Afraid of Detroit?", body: "(Dirtybird Records) It’s official, Medicinalsounds.com is 50 post deep. And to celebrate our 50th is a proper ‘Classic Cut’. It comes from head honcho at Dirtybird, Calude VonStroke and his classic track ‘Who’s Afraid Of Detroit?’. Deep dark Detroit techo at it’s finest. Released back in November 2006, it sounds as good today as it it did then. Hit play and remind yourself how good this one is...", soundcloud: "https://soundcloud.com/claudevonstroke/whos-afraid-of-detroit-db005", created_at: DateTime.new(2013, , ))

Post.create!(title: "Tuesday Born ft. Dnaë – Wake (Two Inch Punch Remix)", body: "(Audio Doughnuts) Here’s another beautiful reworking from Two Inch Punch. This time it’s the work 21 year old jazz based pianist, Gabriel Benn, aka Tuesday Born who get the treatment. Sleepy rolling bass and twisted vocals that have become so familiar of the T.I.P sound. The ‘Singing In The Dark’ EP, complete with Pale and Two Inch Punch remixes is available now.", created_at: DateTime.new(2013, , ))

Post.create!(title: "Jeremy Olander – Factures", body: "(Sudbeat) Jeremy Oldander comes back a little deeper and a little darker. His follow up to the anthemic ‘Let Me Feel‘ takes us on mystical journey. Whist taking things deeper with a more tech-house vibe, Olander keeps that signature Swedish melody and the drop is delicious. Released on Hernan Cattaneo’s Sudbeat, it will form part of the labels first compilation, simply called ‘Sudbeats’. The track is available now on Beatport.", soundcloud: "https://soundcloud.com/jeremyolander/factures", created_at: DateTime.new(2013, , ))

Post.create!(title: "Josef Salvat – Hustler", body: "The follow up to Josef Salvat’s first single, ‘This Life’, comes in the form of ‘Huster’. Minor piano with surprisingly honest lyrics and an echoing beat make for a musing track. I have to say this young Australian reminds me of a male Lana Del Ray, which is no bad thing. Having received praise from various critics it will be interesting to see where new material takes Josef over the course of this year.", soundcloud: "https://soundcloud.com/josef-salvat/josef-salvat-hustler", created_at: DateTime.new(2013, , ))

Post.create!(title: "Polica – Tiff (Feat. Justin Vernon)", body: "Bon Iver frontman, Justin Vernon lends his vocals to Polica’s latest track. It’s seems like a very natural pairing, and the stripped back percussion and minimal instruments seem to echo a more electronic version of the Bon Iver sound. Debuted at Coachella recently, the smooth R&B rhythm provides the background for the velvety voice of Leaneagh with Vernon providing the backing vocals. Warm and rich sounding with a smooth undertone. A nice preview of the forthcoming album due later this year.", soundcloud: "https://soundcloud.com/polica/tiff", created_at: DateTime.new(2013, , ))

Post.create!(title: "I/O – Wasted My Time", body: "(Noizy Cricket) Ever wondered what a bad acid trip would be like? Well I imagine it would be not too dissimilar to this rather haunting video from I/O (born Ayo Olatunji). Directed by BRTHR it is beautiful and terrifying in equal measures. Taken from his ‘Isolation EP’ this introspective and mesmerising track will take you on a journey. Sit back, hit play and enjoy the ride.", soundcloud: "https://www.youtube.com/watch?v=gU7fripmU-s", created_at: DateTime.new(2013, , ))

Post.create!(title: "London Grammar – Wasting My Young Years", body: "This one is hot off the press. The third release from London Grammar, follows on perfectly from ‘Hey Now‘ and ‘Metal and Dust‘. Opening with stings and choral voices give way to the familiar sounds of Hannah’s vocals accompanied by piano and sliding guitar. Simple, stripped back, slowly building and breaking down. Another wistful and reflective offering from the group.", soundcloud: "https://soundcloud.com/londongrammar/london-grammar-wasting-my", created_at: DateTime.new(2013, , ))

Post.create!(title: "Action Bronson – Compliments 2 The Chef", body: "The latest track from everyones favorite Albanian American chef turned rapper; Action Bronson. The easy flow over laid back production from Harry Fraud just melts into your ears. Add in the vocals of Lauriana Mae for the chorus and you’ve got yourself a certified summer cruising track. You can download a copy from RosenbergRadio on their Soundcloud page. Enjoy.", soundcloud: "https://soundcloud.com/rosenbergradio/compliments-2-the-chef-feat", created_at: DateTime.new(2013, , ))

Post.create!(title: "Mark Knight – Your Love", body: "(Tool Room Records) Here’s the new video for the hotly anticipated next release from the legendary Mark Knight. I appreciate that this is the second post regarding Mr Knight in as many days, but I make no apologies for that. When the music’s this good it needs to be shared. The head honcho at Tool Room Records has done it again. Clean percussion, funky bassline and deep filtered vocals make for a surefire club banger. I like the nod towards a certain Australian pop star to. Expect to be hearing this at clubs, festivals and all over the White Isle this summer. Due for release on 22/04/13 on Beatport. Stream the video above until then.", soundcloud: "https://www.youtube.com/watch?v=lVgerFg0FWU", created_at: DateTime.new(2013, , ))

Post.create!(title: "New Order – Blue Monday", body: "(Factory Records) At Medicinal Sounds we always endeavour to improve you listening experience. That’s why we’ve added the ‘Classic Cuts’ section to the site. Here you’ll find tracks that you may have forgotten about or just missed the first time round. And what better way to start than with the biggest selling 12″ of all time. Originally released in 1983, it has been sampled and remixed countless times since. The track starts with the distinctive kick drum before the sequencer melody fades in. Then comes the signature bass line synth overlaid with bass guitar leads. I’ve heard this track in various different environments including the last song at a warehouse rave; it always sounds great.", soundcloud: "https://www.youtube.com/watch?v=2x9mfgUsIis", created_at: DateTime.new(2013, , ))

Post.create!(title: "Mark Knight – Alright", body: "One of my best memories of last year was seeing Mark Knight drop this track at Space, Ibiza – It. Went. Off! I have long been a fan of this man, and this track along with ‘Man With The Red Face‘ are two of my all time favorite house tracks. Knight is a super talented producer and this was recognised with a grammy nomination for his work on the Black Eyed Peas album ‘The-End’. If you haven’t had a listen to his back catalogue I strongly recommend it. The reason this track has came to mind is that he is re-releasing it with Sway providing a new top layer. I’ll be honest I’m entirely not sold on the new version, but maybe that’s because I’m such a fan of the original. Either way have a listen to both and make your own decision. No official release date yet, but will be coming out on Knight’s ‘Toolroom Records‘ in the near future.", soundcloud: "https://www.youtube.com/watch?v=GHgzNReoQRI", created_at: DateTime.new(2013, , ))

Post.create!(title: "Jessie Ware – Imagine It Was Us", body: "(Universal Island Records) The latest offering from Miss Ware and it’s a perfect slice of feel good summer vibes. But then again with Julio Bashmore on the production I would expect nothing less. I have to say I really like Jessie Ware. She seems like a genuine and down to earth pop star with a real passion for music, which is a lot more than can be said for a lot of her contemporaries. Bashmore’s funky bassline and guitars marry perfectly with Jessie’s voice and I hope to her the two of them teaming up again soon.This track is available now, and is part of special re-release of Ware’s ‘Devotion‘ album along with a special remix of ‘Wildest Moments‘ featuring rapper d’jour A$AP Rocky. Well worth a listen too.", soundcloud: "https://www.youtube.com/watch?v=1bmaUt6Wh5k", created_at: DateTime.new(2013, , ))

Post.create!(title: "TNGHT – Acrylics", body: "(LuckyMe x Warp Records) Hudson Mohawke (Ross Birchard) and Lunice (Lunice Fermin Pierre II) make up DJ duo TNGHT. The pair originally met in 2008 when Lunice booked Mohawke to play at his ‘Turbo Crunk’ parties. It wasn’t until 2012 that they released their ‘TNGHT EP’. After releasing ‘Higher Ground‘ last year they come back strong with this latest offering. Big frantic electro complete with an unnerving breakdown – using a child’s musicbox. Serious stuff.", soundcloud: "https://www.youtube.com/watch?v=Gm7XRkpkti4", created_at: DateTime.new(2013, , ))

Post.create!(title: "DFRNT – Nobody Stop Me", body: "(Fina) Alex Cowles, aka DFRNT, is a rather talented young Scotsman to say the least. Blogger, DJ, producer, designer are but a few of his interests. Check out his website for a taste. Based in Edinburgh, he makes effortless deep floating techo and house. Have a listen to this preview of his latest EP, ‘Nobody Stop Me’. Hazy melodies with a steady relaxed beat and warming vocals. I imagine this would sound pretty terrific next to a pool, in the sun, with an ice cold beer. Bring on summer.", created_at: DateTime.new(2013, , ))