Post.create!(title: "Kidnap Kid – Survive", body: "(Black Butter Records) I’ve been aware of Kidnap Kid aka Matt Relton for a while now, but haven’t been blown away by his work to date. Don’t get me wrong; I don’t hate it (and you don’t become iTunes ‘Best Electronic Song of 2012′ as he did with ‘Vehl’ without some serious talent), I just felt his tunes were lacking something. And I think this track has found that something. ‘Survive’ is 7 minute 30 second piece of beautifully crafted deep house. The off beat lick, the soulful vocals, the uplifting melodies, the deep rolling bass – all the elements perfectly combined to make a delicious piece of house music. Congratulations Mr Relton; you’ve just gained a new fan.", soundcloud: "https://soundcloud.com/kidnap_kid/survive", created_at: DateTime.new(2013, 7, 14))

Post.create!(title: "Dusky – Mr Man", body: "I know, I know, yet another post about Dusky!? Well I’m afraid so good readers. And after seeing them at Glastonbury and then hearing this new track and can assue you it’s a case of credit where credit is due. This latest offering from the duo is sublime once again. The warming bass line giving way to a sparse and haunting piano breakdown, before slowing bringing in the snare and building the track back up. Deep glowing house music from one of my favorite producer duo’s around. Due for release as part of Anjunadeep 05 on 27/07/13.", soundcloud: "https://soundcloud.com/duskymusic/dusky-mr-man", created_at: DateTime.new(2013, 7, 10))

Post.create!(title: "J.Rabbit – Tequila Remix", body: "(Spinnin’ Records) Hello ladies and gents, apologies for the lack of posts over the last week or so. I like about 100,000 other music lovers was at Glastonbury. If you weren’t lucky enough to get a ticket we’ve added some content to our Facebook page to give you a very small taste of what went on. While you’re there why not give us a ‘Like’. Anyway back to business, whist stumbling around in a drunken haze on Saturday morning on the way back to my camp site, I came across a little stage playing a heady mix of house, dubstep, trap and disco. I have no idea who the DJ was but he dropped this ‘Tequila’ trap remix and it went off.  So here it is for all to enjoy.", soundcloud: "https://soundcloud.com/jrabbit/j-rabbit-tequila-remix-free", created_at: DateTime.new(2013, 7, 4))

Post.create!(title: "Catching Flies – The Long Journey Home EP", body: "(Indigo Soul) Catching Flies latest EP, ‘The Long Journey Home’ is simply sublime. The 22 year old made a big impression with his first EP ‘The Stars’ last year. This follow up is top quality, down tempo music, with all three tracks delivering the goods. The two remix aren’t half bad either. Available now, get hold of a copy and see for yourself.", soundcloud: "https://soundcloud.com/catchingfliesmusic/the-long-journey-home", created_at: DateTime.new(2013, 7, 17))

Post.create!(title: "Catching Flies – Grey Skies", soundcloud: "https://soundcloud.com/catchingfliesmusic/grey-skies", created_at: DateTime.new(2013, 7, 17))

Post.create!(title: "Catching Flies - Stay Forever", soundcloud: "https://soundcloud.com/catchingfliesmusic/stay-forever", created_at: DateTime.new(2013, 7, 17))

Post.create!(title: "Disclosure – You & Me (Flume Remix)", body: "Disclosure really are flying high right now. Headlining festivals, curating an upcoming Warehouse project and a number one album to boot. As a result its hardly surprising that they’re THE act to remix at the moment. I was sold hook, line and sinker on the Baauer Remix of ‘You & Me‘, but this reworking from Australian producer Flume has given me food for thought. Less frantic in it’s nature, the track takes on a more glich hop style, that works really nicely. I eagerly await more from Flume in the near future.", soundcloud: "https://soundcloud.com/flume/disclosure-you-me-flume-remix", created_at: DateTime.new(2013, 7, 11))

Post.create!(title: "Booka Shade – In White Rooms", body: "(Get Physical Music) Every 10th post here on Medicinal Sounds we like add to our ‘Classic Cuts‘ section. So here to join those already in the hall of fame is Booka Shade with ‘In White Rooms‘. The German house duo is comprised of Walter Merziger and Arno Kammermeier. They’ve been described as veterans of the German electronic music scene, and are renowned for their visually impressive shows; wowing audiences with percussion and re workings live on stage. This is a gorgeously simple track that slowly builds in intensity, never quite reaching the frantic crescendo that much of todays producers do; but that in itself is part of the charm. For me this was the standout track on their ‘Movements’ album, but if you want something something  a bit more jacking, have a listen to ‘Blue Rooms‘ for a techier reworking. Originally released back in May 2006 it sounds as good today as it did then. If you like this check out ‘Mandarine Girl‘, ‘Body Language‘, or any of the rest of their back catalogue.", soundcloud: "https://soundcloud.com/olyspirit/in-white-rooms-booka-shade-original-mix", created_at: DateTime.new(2013, 7, 10))

Post.create!(title: "Kings Of Leon – Closer (No One 32 Remix)", body: "Here’s a nice little remix of my favorite Kings Of Leon track ‘Closer’, courtesy of No One 32. I can’t find out much about this German DJ/ producer, other than his real name, Andreas Leitel, on his Soundcloud page. It puts a nice deep house spin on the track whist keeping Caleb Followill’s emotional vocals at the heart of the tune.", soundcloud: "https://soundcloud.com/no-one-32/closer-no-one-32-vocal-rmx", created_at: DateTime.new(2013, 7, 5))

Post.create!(title: "Close Feat. Joe Dukie – My Way (Dusky Remix)", body: "It’s two for two with Dusky here on medicinalsounds.com, with two mentions in as many posts. This time they take on Will Saul’s alias – Close. They give the melodic deep house treatment to his second single ‘My Way’, taken from forthcoming album ‘Get Closer’. Just further proof of Dusky’s ability and intent. Smooth deep house vibes, whilst keeping Joe Dukie’s vocals (of Fatt Freddie’s Drop) clean and true. Sounding good on a sunny evening.", soundcloud: "https://soundcloud.com/duskymusic/my-way-dusky-remix", created_at: DateTime.new(2013, 7, 2))

Post.create!(title: "Dusky – Vanishing Point", body: "(Naked Naked) Here’s the latest single from Dusky, the London based duo comprised of Alfie Granger-Howell and Nick Harriman. Formerly known as Solarity, the pair may have changed their name but are still producing their distinctive rich melodic sound. This track is no exception with it’s warm deep bass line and steady hi-hat ticking through this is sure to have the dance floors moving. It froms part of their forthcoming EP of the same name, due for release on 03/06/13. You can stream a preview on their Soundclound page now. If you like this check out their remix of Justin Martin’s ‘Don’t Go‘.", soundcloud: "https://soundcloud.com/duskymusic/vanishing-point", created_at: DateTime.new(2013, 5, 28))

Post.create!(title: "Fatboyslim – Praise You (Maribou State Remix)", body: "(Skint Records) It takes a brave individual to take on a stone cold classic like Norman Cook’s ‘Praise You’. In this case it took two, in the form of Maribou State. I first heard of this duo on their collaboration with Pedestrian – ‘Mask‘. This reworking is an equally ambient and floating affair to start with before adding in those classic vocals and slowly building up the energy. It appears fortune does indeed favour the brave. Available for download on Beatport now.", soundcloud: "https://soundcloud.com/fatboyslim/fatboy-slim-praise-you-maribou", created_at: DateTime.new(2013, 5, 27))