Post.create!(title: "Disclosure – When A Fire Starts To Burn", body: "(PMR Records) It’s fair to say the Disclosure boys are gaining rather a large fan base. With their album still unreleased, they managed to get over 40,000 plays of this track in the first hour of uploading it to their soundcloud! ‘When A Fire Starts To Burn’ is the latest track to be previewed from the Lawrence brothers’ ‘Settle’ album due for release on 03/06/13. Apparently the boys found the sample for the track by typing “motivational speaker Harlem” into iTunes. The aim to was to collaborate with a rapper, but I feel this sample has worked out rather well instead. The tune is slightly more minimal take on the melodic house they’ve become renowned for. If you manage to get hold of tickets to their secret album launch party, feel free to invite us.", soundcloud: "https://soundcloud.com/disclosuremusic/when-a-fire-starts-to-burn", created_at: DateTime.new(2013, 05, 23))

Post.create!(title: "Retrograde (Finn Pilly Edit)", body: "Here’s a cracking edit of James Blake’s ‘Retrograde’ by Finn Pilly, a.k.a. Finnebassen. I’ve been a fan of this Norwegian since hearing ‘Touching Me‘ for the first time in Ibiza last year. Since then releases including ‘Such A High‘, ‘If You Only Knew‘ and his cover of Prince’s ‘When Doves Cry‘ have made him one of my favorite downtempo producers. Here he takes the originally sobre ‘Retrograde’ and turns it into a sexy deep house classic, all the while maintaining Blake’s sublime vocals. You can download a copy for free from his Soundcloud. Happy Days.", soundcloud: "https://soundcloud.com/finnebassen/retrograde-finn-pilly-edit", created_at: DateTime.new(2013, 5, 22))

Post.create!(title: "Hervé – Lose Control (feat. Seasfire)", body: "This track passed me by when it was released, but I’m glad a stumbled across it on Herve’s soundcloud. It’s a mesmerising, floating piece of music from the head of ‘Cheap Thrills label’. Taken from the album ‘The Art Of Disappearing’ which also features guest performances from Katie Stelmanis of Austra, Maria Minerva and Niki & The Dove. It’s out now so go and get hold of a copy.", soundcloud: "https://soundcloud.com/hervespace/herve-lose-control", created_at: DateTime.new(2013, 5, 19))

Post.create!(title: "Disclosure – You & Me ft. Eliza Doolittle (Baauer Remix)", body: "He’s at it again. This time Baauer has taken on the British brothers, Disclosure, and their latest offering featuring Eliza Doolittle. Like so many of the good new tunes emerging at the moment this was previewed at Coachella and has now made its way onto the web for all to enjoy. Following the success of his remix of AlunaGeorge’s ‘Attracting Flies‘, Baauer has decided rework another of the UK’s hottest electronic acts in Disclosure. He pushes up the tempo, shifts the pitch on the vocals and adds a sprinkling of his trademark Trap style to tie it all together. Slightly different sound here from Baauer, and I like it. A lot. Available for download on 21st of May. Stream it here until then. If you’re after something a bit funkier, check out the original version below. Warming garage vibes.", soundcloud: "https://soundcloud.com/baauer/disclosure-you-me-ft-eliza", youtube: "https://www.youtube.com/watch?v=W_vM8ePGuRM", created_at: DateTime.new(2013, 5, 15))

Post.create!(title: "Raffertie – Benediction", body: "Stirring cover from Raffertie of Hot Natured’s ‘Benediction’. The British boss of micro label ‘Super Recordings’ puts a deeper twist on one of last years summer smashes. With a deep kick drum at the heart of the track and smooth vocals, this is a effortlessly cool tune. You can download the track for free from the Mixmag soundcloud page. What a treat.", soundcloud: "https://soundcloud.com/mixmag-1/free-mp3-raffertie-benediction", created_at: DateTime.new(2013, 5, 13))

Post.create!(title: "Claude VonStroke – Who’s Afraid of Detroit?", body: "(Dirtybird Records) It’s official, Medicinalsounds.com is 50 post deep. And to celebrate our 50th is a proper ‘Classic Cut’. It comes from head honcho at Dirtybird, Calude VonStroke and his classic track ‘Who’s Afraid Of Detroit?’. Deep dark Detroit techo at it’s finest. Released back in November 2006, it sounds as good today as it it did then. Hit play and remind yourself how good this one is...", soundcloud: "https://soundcloud.com/claudevonstroke/whos-afraid-of-detroit-db005", created_at: DateTime.new(2013, 5, 13))

Post.create!(title: "Tuesday Born ft. Dnaë – Wake (Two Inch Punch Remix)", body: "(Audio Doughnuts) Here’s another beautiful reworking from Two Inch Punch. This time it’s the work 21 year old jazz based pianist, Gabriel Benn, aka Tuesday Born who get the treatment. Sleepy rolling bass and twisted vocals that have become so familiar of the T.I.P sound. The ‘Singing In The Dark’ EP, complete with Pale and Two Inch Punch remixes is available now.", created_at: DateTime.new(2013, 5, 12))

Post.create!(title: "Jeremy Olander – Factures", body: "(Sudbeat) Jeremy Oldander comes back a little deeper and a little darker. His follow up to the anthemic ‘Let Me Feel‘ takes us on mystical journey. Whist taking things deeper with a more tech-house vibe, Olander keeps that signature Swedish melody and the drop is delicious. Released on Hernan Cattaneo’s Sudbeat, it will form part of the labels first compilation, simply called ‘Sudbeats’. The track is available now on Beatport.", soundcloud: "https://soundcloud.com/jeremyolander/factures", created_at: DateTime.new(2013, 5, 9))

Post.create!(title: "Josef Salvat – Hustler", body: "The follow up to Josef Salvat’s first single, ‘This Life’, comes in the form of ‘Huster’. Minor piano with surprisingly honest lyrics and an echoing beat make for a musing track. I have to say this young Australian reminds me of a male Lana Del Ray, which is no bad thing. Having received praise from various critics it will be interesting to see where new material takes Josef over the course of this year.", soundcloud: "https://soundcloud.com/josef-salvat/josef-salvat-hustler", created_at: DateTime.new(2013, 5, 8))

Post.create!(title: "Eli & Fur – Nightmares (Hackman Remix)", body: "Here’s another two of my friends making it big; Eli & Fur. The London based DJ duo have been steadily working their way up the ranks and have played along side the likes of Pete Tong and Sasha. They’ve started producing their own music now and it’s pretty great. So good in fact that Hackman has decided to give their latest track, ‘Nightmares’ the once over. Clean beats with uplifting melodies and beautiful filtered vocals provided by Jen (aka Fur). Great track and quality remix as is to be expected from Hackman. So in summary: young, good looking, talented producers and DJing with some of the biggest names in dance music. Yeah things aren’t looking to bad for these two. Looking forward to new stuff from them in the near future. Will keep you posted when I hear it. Check out the original mix below. You can even get hold of a 320 copy from their soundcloud. Add generous to that list.", soundcloud: "https://soundcloud.com/eliandfur/nightmares-hackman-remix-1", created_at: DateTime.new(2013, 4, 29))
