Post.create!(title: "Polica – Tiff (Feat. Justin Vernon)", body: "Bon Iver frontman, Justin Vernon lends his vocals to Polica’s latest track. It’s seems like a very natural pairing, and the stripped back percussion and minimal instruments seem to echo a more electronic version of the Bon Iver sound. Debuted at Coachella recently, the smooth R&B rhythm provides the background for the velvety voice of Leaneagh with Vernon providing the backing vocals. Warm and rich sounding with a smooth undertone. A nice preview of the forthcoming album due later this year.", soundcloud: "https://soundcloud.com/polica/tiff", created_at: DateTime.new(2013, 4, 24))

Post.create!(title: "I/O – Wasted My Time", body: "(Noizy Cricket) Ever wondered what a bad acid trip would be like? Well I imagine it would be not too dissimilar to this rather haunting video from I/O (born Ayo Olatunji). Directed by BRTHR it is beautiful and terrifying in equal measures. Taken from his ‘Isolation EP’ this introspective and mesmerising track will take you on a journey. Sit back, hit play and enjoy the ride.", soundcloud: "https://www.youtube.com/watch?v=gU7fripmU-s", created_at: DateTime.new(2013, 4, 18))

Post.create!(title: "London Grammar – Wasting My Young Years", body: "This one is hot off the press. The third release from London Grammar, follows on perfectly from ‘Hey Now‘ and ‘Metal and Dust‘. Opening with stings and choral voices give way to the familiar sounds of Hannah’s vocals accompanied by piano and sliding guitar. Simple, stripped back, slowly building and breaking down. Another wistful and reflective offering from the group.", soundcloud: "https://soundcloud.com/londongrammar/london-grammar-wasting-my", created_at: DateTime.new(2013, 4, 17))

Post.create!(title: "Action Bronson – Compliments 2 The Chef", body: "The latest track from everyones favorite Albanian American chef turned rapper; Action Bronson. The easy flow over laid back production from Harry Fraud just melts into your ears. Add in the vocals of Lauriana Mae for the chorus and you’ve got yourself a certified summer cruising track. You can download a copy from RosenbergRadio on their Soundcloud page. Enjoy.", soundcloud: "https://soundcloud.com/rosenbergradio/compliments-2-the-chef-feat", created_at: DateTime.new(2013, 4, 17))

Post.create!(title: "Mark Knight – Your Love", body: "(Tool Room Records) Here’s the new video for the hotly anticipated next release from the legendary Mark Knight. I appreciate that this is the second post regarding Mr Knight in as many days, but I make no apologies for that. When the music’s this good it needs to be shared. The head honcho at Tool Room Records has done it again. Clean percussion, funky bassline and deep filtered vocals make for a surefire club banger. I like the nod towards a certain Australian pop star to. Expect to be hearing this at clubs, festivals and all over the White Isle this summer. Due for release on 22/04/13 on Beatport. Stream the video above until then.", soundcloud: "https://www.youtube.com/watch?v=lVgerFg0FWU", created_at: DateTime.new(2013, 4, 16))

Post.create!(title: "New Order – Blue Monday", body: "(Factory Records) At Medicinal Sounds we always endeavour to improve you listening experience. That’s why we’ve added the ‘Classic Cuts’ section to the site. Here you’ll find tracks that you may have forgotten about or just missed the first time round. And what better way to start than with the biggest selling 12″ of all time. Originally released in 1983, it has been sampled and remixed countless times since. The track starts with the distinctive kick drum before the sequencer melody fades in. Then comes the signature bass line synth overlaid with bass guitar leads. I’ve heard this track in various different environments including the last song at a warehouse rave; it always sounds great.", soundcloud: "https://www.youtube.com/watch?v=2x9mfgUsIis", created_at: DateTime.new(2013, 4, 16))

Post.create!(title: "Mark Knight – Alright", body: "One of my best memories of last year was seeing Mark Knight drop this track at Space, Ibiza – It. Went. Off! I have long been a fan of this man, and this track along with ‘Man With The Red Face‘ are two of my all time favorite house tracks. Knight is a super talented producer and this was recognised with a grammy nomination for his work on the Black Eyed Peas album ‘The-End’. If you haven’t had a listen to his back catalogue I strongly recommend it. The reason this track has came to mind is that he is re-releasing it with Sway providing a new top layer. I’ll be honest I’m entirely not sold on the new version, but maybe that’s because I’m such a fan of the original. Either way have a listen to both and make your own decision. No official release date yet, but will be coming out on Knight’s ‘Toolroom Records‘ in the near future.", soundcloud: "https://www.youtube.com/watch?v=GHgzNReoQRI", created_at: DateTime.new(2013, 4, 15))

Post.create!(title: "Jessie Ware – Imagine It Was Us", body: "(Universal Island Records) The latest offering from Miss Ware and it’s a perfect slice of feel good summer vibes. But then again with Julio Bashmore on the production I would expect nothing less. I have to say I really like Jessie Ware. She seems like a genuine and down to earth pop star with a real passion for music, which is a lot more than can be said for a lot of her contemporaries. Bashmore’s funky bassline and guitars marry perfectly with Jessie’s voice and I hope to her the two of them teaming up again soon.This track is available now, and is part of special re-release of Ware’s ‘Devotion‘ album along with a special remix of ‘Wildest Moments‘ featuring rapper d’jour A$AP Rocky. Well worth a listen too.", soundcloud: "https://www.youtube.com/watch?v=1bmaUt6Wh5k", created_at: DateTime.new(2013, 4, 15))

Post.create!(title: "TNGHT – Acrylics", body: "(LuckyMe x Warp Records) Hudson Mohawke (Ross Birchard) and Lunice (Lunice Fermin Pierre II) make up DJ duo TNGHT. The pair originally met in 2008 when Lunice booked Mohawke to play at his ‘Turbo Crunk’ parties. It wasn’t until 2012 that they released their ‘TNGHT EP’. After releasing ‘Higher Ground‘ last year they come back strong with this latest offering. Big frantic electro complete with an unnerving breakdown – using a child’s musicbox. Serious stuff.", soundcloud: "https://www.youtube.com/watch?v=Gm7XRkpkti4", created_at: DateTime.new(2013, 4, 14))

Post.create!(title: "DFRNT – Nobody Stop Me", body: "(Fina) Alex Cowles, aka DFRNT, is a rather talented young Scotsman to say the least. Blogger, DJ, producer, designer are but a few of his interests. Check out his website for a taste. Based in Edinburgh, he makes effortless deep floating techo and house. Have a listen to this preview of his latest EP, ‘Nobody Stop Me’. Hazy melodies with a steady relaxed beat and warming vocals. I imagine this would sound pretty terrific next to a pool, in the sun, with an ice cold beer. Bring on summer.", created_at: DateTime.new(2013, 4, 11))