Post.create!(title: "Indiana – Bound", body: "Nottingham based singer Indiana releases her new single ‘Bound’. Having spent five of the best years of my life in Nottingham, I alway feel a strange sense of excitement and pride when I hear about new artist from the area breaking through.After catching the attention of a few bloggers last year with her haunting cover of Frank Ocean’s ‘Swim Good‘, Indiana looks sets to grab the limelight with ‘Bound’. It’s an undeniably sexy track with her powerful vocals, big steady bass drum heartbeat and sensual guitar power cords all combing in a heady mix. Tantalising stuff.", soundcloud: "https://soundcloud.com/indianathegirl/bound", created_at: DateTime.new(2013, , ))

Post.create!(title: "Wretch 32 ft Shakka – Blackout", body: "The latest offering from 28 year old rapper Wretch 32. Born Jermaine Scott, the Tottenham rapper first broke onto the scene in 2009 when he appeared on the BBC Introducing Stage at the Radio 1 Big Weekend. He was then nominated for the BBC sound of 2011 short list. His first single ‘Traktor‘ (which incidentally makes finding any information regarding NI’s DVS of the same name much harder than it should be) was the lead single from his second studio album ‘Black & White’. ‘Blackout’ is the first single to be released from Wretch’s forthcoming, as yet unnamed, third album. It features the vocals of Shakka, a vocalist Wretch found on Youtube and ask to work with. Knox Brown, a relatively unknown producer from Birmingham takes care of the production on this track, which I feel is pretty top notch. Recently previewed on MistaJam’s 1Xtra show, I think this is going to be a big hit.", soundcloud: "https://soundcloud.com/wretch32/wretch-32-ft-shakka-blackout", created_at: DateTime.new(2013, , ))

Post.create!(title: "Teenage Mutants & Andre Crom – Hanging On", body: "(OFF Recordings) Two Deep House forces, one old and one new, come together to make this fantastic tune. Teenage Mutants originally started as a duo two years ago, before continuing as a one-man-band DJ and producer. His first release on OFF Recordings sees him team up with the founder of the label, Andre Crom. Having been a DJ and producer for a number of years, it wasn’t until Crom moved to Berlin in 2008 and started the record label that things really started to take off. SIne then his success is proven by a host of singles in the Beatport Deep House Chart. The track samples The Supremes’ 1966 single ‘You Keep Me Hanging On’, and turns it into a Deep House smash for 2013. Based on this, I hope these two Germans continue to work together in the future.", created_at: DateTime.new(2013, , ))

Post.create!(title: "Rhye – Open (Ryan Hemsworth Remix)", body: "(Loma Vista Recordings) Canadian prodcer Ryan Hemsworth puts his twist on Rhye’s ‘Open’. Whist making a name for himself as a producer for some exciting new rap artisits such as Main Attrakionz and Deniero Farrar, Hemsworth has also put out some excellent material as a solo artist. His ‘Last Words‘ EP released in conjunction with the Wedidit Crew, whist having an unmistakable hip-hop backbone, also infuses other influences with elements of electro pop, guitar rock and chilled out ambience. This remix is a beautiful reworking, keeping the clean vocals and layering up with a deep rolling bass and extra little touches of percussion scattered on top. Top quality work. If you wan’t to find out a bit more about the young Canadian, Fact did a nice little interview last year, before putting out the guest mix he did for them, which is definitely worth a listen.", soundcloud: "https://soundcloud.com/rhyemusic/open-ryan-hemsworth-remix", created_at: DateTime.new(2013, , ))

Post.create!(title: "London Grammar – Metal & Dust", body: "(Metal & Dust Recordings) The London Trio follow up their debut single ‘Hey Now‘ with the equally mesmerising ‘Metal And Dust’. The beautiful stripped back vocals of Hannah Reid in the beginning, simply complimented by sliding guitar works perfectly. Then in comes the shuffling percussion, with a cool air of Massive Attack, to tie it all together into a sublime, slow building finish. The band are busy recording new material and putting the finishing touches on their live act, which I hope be able to see. I fully expect them to be featuring at a few festivals this year so keep your ears to the ground. This track was selected as a hottest record in the world for Zane Lowe and with good reason.  A wonderful follow up to their etherial first offering. Available now on the bands own Record Label – Metal & Dust.", soundcloud: "https://soundcloud.com/londongrammar/metalanddust", created_at: DateTime.new(2013, , ))

Post.create!(title: "Michael Woods – Platinum Chains", body: "(Fly Eye) Born and raised in Hackney, London, Michael Woods still works out his studio in East London. Since the release of his debut single ‘Warrior‘, the British producer has had a fairly incredible journey. As well as numerous solo releases he has also had collaborations with the likes of Chris Lake, Funkagenda & Mark Knight. After gaining notoriety in the dance scene, various mainstream artists including Kylie, Estelle, The Ting Tings, The Temper Trap and P Diddy have all borrowed his insatiable remixing skills. He was also responsible for the production on Example’s number one single ‘Changed The Way You Kissed Me‘. After this Michael secured a summer residency for Cream at Amnesia in Ibiza, while the ever discerning Deadmau5 invited him on his infamous 2010 UK tour. All these accolades lead to a nomination for ‘Best Remixer’ at the 2011 IDMA’s (International Dance Music Awards). ‘Platinum Chains’ is the latest offering from Mr Woods. It combines beautifully crafted melodies, epic build and hands in the air drop with a huge stuttering bass. This Woods at his finest. Stream the preview above until the release on March 11th.", soundcloud: "https://soundcloud.com/michaelwoods/michael-woods-platinum", created_at: DateTime.new(2013, , ))

Post.create!(title: "Flux Pavilion – Blow The Roof", body: "(Circus/Big Beat/ Atlantic) Flux Pavilion, christened Joshua Steele is a British producer and DJ. Together with Doctor P and DJ Swan-E he co-founded Circus Records. He went from underground DJ to dubstep superstar  with his 2011 banger ‘Bass Cannon‘. Since then, things have gone from strength to strength. His  track ‘I Can’t Stop‘ was used as a sample for ‘Who Gon Stop Me’ on Jay Z and Kanye West’s album ‘Watch The Throne’. Blow The Roof is the title track from Flux Pavilion’s latest EP, and all of the tracks are well worth a listen. You can also get hold of a free copy of OneTwoThee from Flux’s website.", soundcloud: "https://soundcloud.com/flux-pavilion/flux-pavilion-blow-the-roof", created_at: DateTime.new(2013, , ))

Post.create!(title: "Jakwob – Fade (Club VIP)", body: "(Boom Ting Recordings) Jakwob (aka James Jacob) started gaining attention in 2009 with his remixes of Ellie Goulding’s Starry Eyed and ‘Between The Sheets‘. Sine then the British producer has released several singles on his own record label Boom Ting Records, which may well be the best name for a record label ever. His latest offering ‘Fade’ has the enchanting vocal of Maiday and piano reminiscent of Deadmau5′s ‘Faxing Berlin‘. Jakwob has also made a reworked VIP mix for the club. The original version is below, and the EP is due for release on 17th March.", soundcloud: "https://soundcloud.com/jakwob/jakwob-fade-club-vip-1", created_at: DateTime.new(2013, , ))
