Post.create!(title: "Rachel Row – Follow The Step ( Justin Martin Remix)", body: "(Pets Recordings) He’s done it again. This time Mr Martin has put his touch on Rachel Row’s ‘Follow The Step’. There are a couple of remixes of this young Bulgarian’s new single, but the Justin Martin remix is the stand out one for me. I love the contrast of warped bass against the twinkling high melodies midway through. Bringing his trademark superior production skills onboard this track is top quality. Like ‘Mask‘ this track is also due to be released on the ‘Friends Will Carry You Home Too’ compilation album from Pets Recordings. I eagerly await it’s release. There’s a lengthy preview above or the official video of the original track is below if you want to know what Rachel Row looks like.", youtube: "https://www.youtube.com/watch?v=feswgeM1yKA", created_at: DateTime.new(2013, , ))

Post.create!(title: "Pedestrian & Maribou State – Mask", body: "(Pets Recordings) UK duo Maribou State have joined forced with Pedestrian to make this beautiful floating piece of house. Starting their journey in 2011 after playing at the club night WAYF. Later that year a mix created for Hush House was heard by TFA who promptly signed them to the label. However it wasn’t until ‘Olivia‘ was released that the pair really started to be noticed. Since then remixes of 2 Bears, Wretch 32 and Crookers have helped them to continue to gain momentum. Pedestrian (aka Jack SIbley) is the other producer involved in this number. Combining high production ability with super tight mixing skills this is young man is a real all rounder. His debuet 12′ ‘Hei Poi‘ was received with critical acclaim. With DJ sets which vary from luxurious, melodic beats, right through to the nastiest basslines that hip hop, house, garage and everything in between have to offer. Unlike many other DJs Pedestrain prides himself on having unique sets, tailoring each performance to the crowd in attendance.  His back to back set with Gangcolours at Boiler Room is well worth a watch. The two have worked together on a few projects but I feel ‘Mask’ is their best offering yet. Easy vocals with sliding synths and a steady shuffling beat. Goodbye winter, hello spring. ‘Mask’ features on a new compilation album by the name ‘Friends Will Carry You Home Too’ which is released on March 18th. The official video is below.", soundcloud: "https://soundcloud.com/pedestriansound/pedestrian-maribou-state-mask", youtube: "https://www.youtube.com/watch?v=ZU5zK5vn6WA", created_at: DateTime.new(2013, , ))

Post.create!(title: "Joey Bada$$ – Waves", body: "(SOW) There are a lot of second rate rappers emerging at moment, but thankfully Joey Bada$$ isn’t one of them. The Brooklyn boy sounds like he’s been doing this for decades, which is unlikely seeing as he’s only 17! This laid back track is effortlessly cool, with mellow beats and a funky bassline. A perfect cruising tune. After releasing two mixtapes with his hip-hop collective Pro.Era, the rapper is now set to drop his first full album in 2013. Big things to come.", youtube: "https://www.youtube.com/watch?v=51e1gIkzHgk", created_at: DateTime.new(2013, , ))

Post.create!(title: "Dimitri Vegas, Moguai & Like Mike – Mammoth", body: "(Spinnin Records) Given the quality of Belgium footballers at present I’m considering putting a tenner on them for the next world cup, and based on this track their DJs are producing the goods as well. The Belgium brothers Dimitri Vegas and Like Mike have teamed up with the German giant Moguai to produce this absolute banger. The combination of twisted synths, huge bass and high energy ensure that this track will be a festival smasher in 2013. If anyone manages to get hold of tickets to Tomorrow Land expect to be hearing this one in more than one set. The decidedly unoffical “Official’ video can be seen below, which I have included simply because it’s a pretty amazing video.", soundcloud: "https://soundcloud.com/dimitrivegasandlikemike/dimitri-vegas-moguai-like-mike", youtube: "https://www.youtube.com/watch?v=ZKowwPqZCD0", created_at: DateTime.new(2013, , ))

Post.create!(title: "Rudimental – Spoons feat. MNEK & Syron (Two Inch Punch Remix)", body: "(Black Butter Records) Rudimental are a quartet from Hackney who have gone from strength to strength since the release of their single ‘Feel The Love’ in 2012. The group are renowned for their high energy performances on stage and are due to start their own headline tour in April 2013, which I hope to get tickets to. Rudimental have managed to secure top quality vocalists for their singles and this time they’ve teamed up with MNEK and Syron, deciding not to enlist the help of John Newman on this occasion. I particularly like the Two Inch Punch Remix of this track. I first caught wind of this producer a few years back when a friend found the Birdy track ‘People Help The People‘ remix. Again going in with the distorted vocals and rolling bass this tune is somehow both cold and warming at the same time. Have a listen a see what you think. If you go to the sites website you can get hold of this remix for free in exchange for your email, or just steam it below.", soundcloud: "https://soundcloud.com/rudimentaluk/spoons-two-inch-punch-remix", youtube: "https://www.youtube.com/watch?v=a9iZh5lV13M", created_at: DateTime.new(2013, , ))

Post.create!(title: "London Grammar – Hey Now", body: "This track is both beautiful and haunting in equal measures. There isn’t much info about this band other than that they are a ‘London trio’ consisting of Hannah, Daniel and Dot. This tune has an air of The XX about it, with the strong female vocal, soft reverberating drums and floating guitars. The Dot Major Remix gives it a nice twist if you’re after something with a higher BPM. Check it out below. Perfect hangover music.", youtube: "https://www.youtube.com/watch?v=MTvHcQmKUpU", soundcloud: "https://soundcloud.com/londongrammar/hey-now-dot-major-remix", created_at: DateTime.new(2013, , ))

Post.create!(title: "Chris Malinchak – So Good To Me", body: "(French Express) I heard this track a few months back on my way to a 12 hour nights shift and it made me smile. Any song capable of doing that I think deserved to be shared. A true feel good tune by the NYC producer. Great melodies with soulful vocals. A class act all the way.", soundcloud: "https://soundcloud.com/chrismalinchak/so-good-to-me", created_at: DateTime.new(2013, , ))

Post.create!(title: "Jeremy Olander – Let Me Feel", body: "(Pryda Friends) I have to say this talented Swede is fast becoming my new favorite producer. Not only did he give away his last two tracks, ‘Put Out’ and ‘Pusher‘ for free, but the quality seems to improve with each new release. But then with a mentor like Eric Prydz, quality is to be expected. His tracks have a certain air of early Deadmau5 to them, and I feel he is well on his way to establishing himself as a house hold name in progressive music. This tune builds beautifully, with great melodies and a catchy vocal – textbook anthemic house music. I for one cannot wait for new material from Mr Olander, but am happy listening to this top quality track in the mean time.", soundcloud: "https://soundcloud.com/jeremyolander/jeremy-olander-let-me-feel", created_at: DateTime.new(2013, , ))

Post.create!(title: "Fly O Tech - Spacetacular", body: "(Cream Couture Records) Demian Muller and Ernesto Yoga make up Fly O Tech. Muller is on vocals while Yoga is a multi-instrumenalist in the duo. “Beginning with watery electronic beats, to feel and follow the dancing rain right through and into your soul, Fly-O-Tech pulls, swims in deeper emotions, but comforts that this slow drop will be lifted. If not by the sweet vocals, then by the beautiful symphony of life captured by a solo piano. The rain falls, the music plays, you wade through the beats, and then that call – a completed circle of a personal and unified journey, created for you by Fly-O-Tech.” Or so their Soundcloud page says. I’m no so sure about all that, but I do know that I really enjoy this track, and I hope you do to. Their new track Twilight is also well worth a listen.", youtube: "https//www.youtube.com/watch?v=TzVzQn-zM5M", created_at: DateTime.new(2013, , ))

Post.create!(title: "A$AP Rocky - Wild For The Night", body: "(Columbia) What do you get when you cross arguably the biggest name in dub step with one of the most exciting new rappers on the scene? This track. After releasing a few mixtapes this is the debut single from Rakim Mayers’ first full length album; Long Live A$AP. I’ve been a fan of A$AP since I first heard Goldie last year. I’ll admit I wasn’t sure about this track when I first heard it but it’s really grown on me.", soundcloud: "https://soundcloud.com/asvpxrocky/wild-for-the-night", created_at: DateTime.new(2013, , ))