Post.create!(title: "Harlem Shake", body: "Legendary Hip Hop producer Justin Smith aka Just Blaze, has teamed up with one of the champions of Trap music to make this absolute banger. Baauer Has been going from strength to strength since releasing one of the biggest underground tracks of last year – Harlem Shake. Enjoy this pairing, just be careful you don’t blow your speakers!", created_at: DateTime.new(2013, , ))

Post.create!(title: "Justin Martin - Don't Go (Dusky Remix)", body: "(Dirtybird Records) I am a big fan of the original version of this track by the co-founder of the Dirtybird crew, but the Dusky remix gives it a nice twist. The Lodon duo have steadily been gaining momentum and 2013 looks set to be a big year for them. Watch this space.", youtube: "https://www.youtube.com/watch?v=ANP_BkWVkLI", created_at: DateTime.new(2013, , ))

Post.create!(title: "Jamie Woon - Wayfaring Stranger (Burial Mix)", body: "I like many people am rather excited by the news that the living legend Burial is releasing new material. Here he is remixing Jamie Woon. This is one of my all time favorite tracks, deep dark and full of emotion. Hit play and enjoy the journey.", youtube: "https://www.youtube.com/watch?v=HSe4CxEvFiE", created_at: DateTime.new(2013, , ))

Post.create!(title: "Kuhn - I Quit (Time Wharp Remix)", body: "(Civil Music) I’m liking this Time Wharp remix. Available on Kuhn’s ‘Kings’ EP which you can get hold of here. This deep rolling track is cooler than Jay Z’s fridge.", youtube: "https://www.youtube.com/watch?v=4LlCbq7KXi8", created_at: DateTime.new(2013, , ))

Post.create!(title: "Tony Romera - Pandor (Original Mix)", body: "(Protocol) This is BIG from Tony Romera. Based in Lyon, France, he’s falls in to the category of successful international DJs who is also frustratingly young. With support from the likes of Tiesto, Roger Sanchez, Chuckie and Steve Aoki to name but a few it’s fair to say the future is looking bright for this Frenchman. Turn this one up loud.", youtube: "https://www.youtube.com/watch?v=4LlCbq7KXi8", created_at: DateTime.new(2013, , ))

Post.create!(title: "Duke Dumont - The Giver (Original Mix)", body: "(Turbo Recordings) I first heard about Duke Dumont with his remix of Mystery Jet’s ‘Two Doors Down’. That was back in 2009 and since then he’s fallen of my radar, but the UK producer has been busy recently with remixes for Santigold and AlunaGeorge. He’s come back in fine form with this fantastic slice of House. Its a “feel good vocal house anthem.” Enjoy.", youtube: "https://www.youtube.com/watch?v=EoyDZD7e6Us", created_at: DateTime.new(2013, , ))

Post.create!(title: "Voyeur - Blame It On The Youth", body: "(MadTech Records) Feeling this track by Leeds based producer Voyeur. Released on MadTech Records you can get hold of it here. The Keri Chandler Remix is also well worth a listen.", youtube: "https://soundcloud.com/voyeuraudio/blame-it-on-the-youth-clip", created_at: DateTime.new(2013, , ))

Post.create!(title: "Wife - Bodies", body: "Can’t find much about Wife, was introduced to this tune by Loose Synths. I have to admit the video is slightly unnerving. The track is so so good though. I strongly suggest you have a listen and hope you enjoy it half as much as I do.", youtube: "https://www.youtube.com/watch?v=NNQh3I8Pumc", created_at: DateTime.new(2013, , ))

Post.create!(title: "Cyril Hahn - Solange - Losing You...", body: "Cyril Hahn is a young swiss currently living in Vancouver, Canada and making some pretty amazing music. Cannot get enough of this tune at the moment. Just feels so right, chilled autumn vibes.", youtube: "https://soundcloud.com/cyrilhahn/solange-losing-you-cyril-hahn", created_at: DateTime.new(2013, , ))