Post.create!(title: "Teenage Mutants & Andre Crom – Hanging On", body: "(OFF Recordings) Two Deep House forces, one old and one new, come together to make this fantastic tune. Teenage Mutants originally started as a duo two years ago, before continuing as a one-man-band DJ and producer. His first release on OFF Recordings sees him team up with the founder of the label, Andre Crom. Having been a DJ and producer for a number of years, it wasn’t until Crom moved to Berlin in 2008 and started the record label that things really started to take off. SIne then his success is proven by a host of singles in the Beatport Deep House Chart. The track samples The Supremes’ 1966 single ‘You Keep Me Hanging On’, and turns it into a Deep House smash for 2013. Based on this, I hope these two Germans continue to work together in the future.", created_at: DateTime.new(2013, 3, 13))

Post.create!(title: "Rhye – Open (Ryan Hemsworth Remix)", body: "(Loma Vista Recordings) Canadian prodcer Ryan Hemsworth puts his twist on Rhye’s ‘Open’. Whist making a name for himself as a producer for some exciting new rap artisits such as Main Attrakionz and Deniero Farrar, Hemsworth has also put out some excellent material as a solo artist. His ‘Last Words‘ EP released in conjunction with the Wedidit Crew, whist having an unmistakable hip-hop backbone, also infuses other influences with elements of electro pop, guitar rock and chilled out ambience. This remix is a beautiful reworking, keeping the clean vocals and layering up with a deep rolling bass and extra little touches of percussion scattered on top. Top quality work. If you wan’t to find out a bit more about the young Canadian, Fact did a nice little interview last year, before putting out the guest mix he did for them, which is definitely worth a listen.", soundcloud: "https://soundcloud.com/rhyemusic/open-ryan-hemsworth-remix", created_at: DateTime.new(2013, 3, 12))

Post.create!(title: "London Grammar – Metal & Dust", body: "(Metal & Dust Recordings) The London Trio follow up their debut single ‘Hey Now‘ with the equally mesmerising ‘Metal And Dust’. The beautiful stripped back vocals of Hannah Reid in the beginning, simply complimented by sliding guitar works perfectly. Then in comes the shuffling percussion, with a cool air of Massive Attack, to tie it all together into a sublime, slow building finish. The band are busy recording new material and putting the finishing touches on their live act, which I hope be able to see. I fully expect them to be featuring at a few festivals this year so keep your ears to the ground. This track was selected as a hottest record in the world for Zane Lowe and with good reason.  A wonderful follow up to their etherial first offering. Available now on the bands own Record Label – Metal & Dust.", soundcloud: "https://soundcloud.com/londongrammar/metalanddust", created_at: DateTime.new(2013, 3, 3))

Post.create!(title: "Michael Woods – Platinum Chains", body: "(Fly Eye) Born and raised in Hackney, London, Michael Woods still works out his studio in East London. Since the release of his debut single ‘Warrior‘, the British producer has had a fairly incredible journey. As well as numerous solo releases he has also had collaborations with the likes of Chris Lake, Funkagenda & Mark Knight. After gaining notoriety in the dance scene, various mainstream artists including Kylie, Estelle, The Ting Tings, The Temper Trap and P Diddy have all borrowed his insatiable remixing skills. He was also responsible for the production on Example’s number one single ‘Changed The Way You Kissed Me‘. After this Michael secured a summer residency for Cream at Amnesia in Ibiza, while the ever discerning Deadmau5 invited him on his infamous 2010 UK tour. All these accolades lead to a nomination for ‘Best Remixer’ at the 2011 IDMA’s (International Dance Music Awards). ‘Platinum Chains’ is the latest offering from Mr Woods. It combines beautifully crafted melodies, epic build and hands in the air drop with a huge stuttering bass. This Woods at his finest. Stream the preview above until the release on March 11th.", soundcloud: "https://soundcloud.com/michaelwoods/michael-woods-platinum", created_at: DateTime.new(2013, 3, 3))

Post.create!(title: "Flux Pavilion – Blow The Roof", body: "(Circus/Big Beat/ Atlantic) Flux Pavilion, christened Joshua Steele is a British producer and DJ. Together with Doctor P and DJ Swan-E he co-founded Circus Records. He went from underground DJ to dubstep superstar  with his 2011 banger ‘Bass Cannon‘. Since then, things have gone from strength to strength. His  track ‘I Can’t Stop‘ was used as a sample for ‘Who Gon Stop Me’ on Jay Z and Kanye West’s album ‘Watch The Throne’. Blow The Roof is the title track from Flux Pavilion’s latest EP, and all of the tracks are well worth a listen. You can also get hold of a free copy of OneTwoThee from Flux’s website.", soundcloud: "https://soundcloud.com/flux-pavilion/flux-pavilion-blow-the-roof", created_at: DateTime.new(2013, 3, 2))

Post.create!(title: "Jakwob – Fade (Club VIP)", body: "(Boom Ting Recordings) Jakwob (aka James Jacob) started gaining attention in 2009 with his remixes of Ellie Goulding’s Starry Eyed and ‘Between The Sheets‘. Sine then the British producer has released several singles on his own record label Boom Ting Records, which may well be the best name for a record label ever. His latest offering ‘Fade’ has the enchanting vocal of Maiday and piano reminiscent of Deadmau5′s ‘Faxing Berlin‘. Jakwob has also made a reworked VIP mix for the club. The original version is below, and the EP is due for release on 17th March.", soundcloud: "https://soundcloud.com/jakwob/jakwob-fade-club-vip-1", created_at: DateTime.new(2013, 3, 1))


Post.create!(title: "Rachel Row – Follow The Step ( Justin Martin Remix)", body: "(Pets Recordings) He’s done it again. This time Mr Martin has put his touch on Rachel Row’s ‘Follow The Step’. There are a couple of remixes of this young Bulgarian’s new single, but the Justin Martin remix is the stand out one for me. I love the contrast of warped bass against the twinkling high melodies midway through. Bringing his trademark superior production skills onboard this track is top quality. Like ‘Mask‘ this track is also due to be released on the ‘Friends Will Carry You Home Too’ compilation album from Pets Recordings. I eagerly await it’s release. There’s a lengthy preview above or the official video of the original track is below if you want to know what Rachel Row looks like.", youtube: "https://www.youtube.com/watch?v=feswgeM1yKA", created_at: DateTime.new(2013, 2, 25))

Post.create!(title: "Pedestrian & Maribou State – Mask", body: "(Pets Recordings) UK duo Maribou State have joined forced with Pedestrian to make this beautiful floating piece of house. Starting their journey in 2011 after playing at the club night WAYF. Later that year a mix created for Hush House was heard by TFA who promptly signed them to the label. However it wasn’t until ‘Olivia‘ was released that the pair really started to be noticed. Since then remixes of 2 Bears, Wretch 32 and Crookers have helped them to continue to gain momentum. Pedestrian (aka Jack SIbley) is the other producer involved in this number. Combining high production ability with super tight mixing skills this is young man is a real all rounder. His debuet 12′ ‘Hei Poi‘ was received with critical acclaim. With DJ sets which vary from luxurious, melodic beats, right through to the nastiest basslines that hip hop, house, garage and everything in between have to offer. Unlike many other DJs Pedestrain prides himself on having unique sets, tailoring each performance to the crowd in attendance.  His back to back set with Gangcolours at Boiler Room is well worth a watch. The two have worked together on a few projects but I feel ‘Mask’ is their best offering yet. Easy vocals with sliding synths and a steady shuffling beat. Goodbye winter, hello spring. ‘Mask’ features on a new compilation album by the name ‘Friends Will Carry You Home Too’ which is released on March 18th. The official video is below.", soundcloud: "https://soundcloud.com/pedestriansound/pedestrian-maribou-state-mask", youtube: "https://www.youtube.com/watch?v=ZU5zK5vn6WA", created_at: DateTime.new(2013, 2, 23))

Post.create!(title: "Joey Bada$$ – Waves", body: "(SOW) There are a lot of second rate rappers emerging at moment, but thankfully Joey Bada$$ isn’t one of them. The Brooklyn boy sounds like he’s been doing this for decades, which is unlikely seeing as he’s only 17! This laid back track is effortlessly cool, with mellow beats and a funky bassline. A perfect cruising tune. After releasing two mixtapes with his hip-hop collective Pro.Era, the rapper is now set to drop his first full album in 2013. Big things to come.", youtube: "https://www.youtube.com/watch?v=51e1gIkzHgk", created_at: DateTime.new(2013, 2, 9))

Post.create!(title: "Dimitri Vegas, Moguai & Like Mike – Mammoth", body: "(Spinnin Records) Given the quality of Belgium footballers at present I’m considering putting a tenner on them for the next world cup, and based on this track their DJs are producing the goods as well. The Belgium brothers Dimitri Vegas and Like Mike have teamed up with the German giant Moguai to produce this absolute banger. The combination of twisted synths, huge bass and high energy ensure that this track will be a festival smasher in 2013. If anyone manages to get hold of tickets to Tomorrow Land expect to be hearing this one in more than one set. The decidedly unoffical “Official’ video can be seen below, which I have included simply because it’s a pretty amazing video.", soundcloud: "https://soundcloud.com/dimitrivegasandlikemike/dimitri-vegas-moguai-like-mike", youtube: "https://www.youtube.com/watch?v=ZKowwPqZCD0", created_at: DateTime.new(2013, 2, 9))